# Sports
Sport.find_or_create_by(name: "Baseball")
Sport.find_or_create_by(name: "Basketball")
Sport.find_or_create_by(name: "Bowling")
Sport.find_or_create_by(name: "Boxing")
Sport.find_or_create_by(name: "Cross Country")
Sport.find_or_create_by(name: "Fencing")
Sport.find_or_create_by(name: "Field Hockey")
Sport.find_or_create_by(name: "Football")
Sport.find_or_create_by(name: "Golf")
Sport.find_or_create_by(name: "Gymnastics")
Sport.find_or_create_by(name: "Ice Hockey")
Sport.find_or_create_by(name: "Lacrosse")
Sport.find_or_create_by(name: "Rifle")
Sport.find_or_create_by(name: "Rowing")
Sport.find_or_create_by(name: "Skiing")
Sport.find_or_create_by(name: "Soccer")
Sport.find_or_create_by(name: "Softball")
Sport.find_or_create_by(name: "Swimming and Diving")
Sport.find_or_create_by(name: "Tennis")
Sport.find_or_create_by(name: "Track and Field")
Sport.find_or_create_by(name: "Volleyball")
Sport.find_or_create_by(name: "Water Polo ")
Sport.find_or_create_by(name: "Wrestling")

# States
State.find_or_create_by(name: "Alabama")
State.find_or_create_by(name: "Alaska")
State.find_or_create_by(name: "Arizona")
State.find_or_create_by(name: "Arkansas")
State.find_or_create_by(name: "California")
State.find_or_create_by(name: "Colorado")
State.find_or_create_by(name: "Connecticut")
State.find_or_create_by(name: "Delaware")
State.find_or_create_by(name: "District of Columbia")
State.find_or_create_by(name: "Florida")
State.find_or_create_by(name: "Georgia")
State.find_or_create_by(name: "Guam")
State.find_or_create_by(name: "Hawaii")
State.find_or_create_by(name: "Idaho")
State.find_or_create_by(name: "Illinois")
State.find_or_create_by(name: "Indiana")
State.find_or_create_by(name: "Iowa")
State.find_or_create_by(name: "Kansas")
State.find_or_create_by(name: "Kentucky")
State.find_or_create_by(name: "Louisiana")
State.find_or_create_by(name: "Maine")
State.find_or_create_by(name: "Maryland")
State.find_or_create_by(name: "Massachusetts")
State.find_or_create_by(name: "Michigan")
State.find_or_create_by(name: "Minnesota")
State.find_or_create_by(name: "Mississippi")
State.find_or_create_by(name: "Missouri")
State.find_or_create_by(name: "Montana")
State.find_or_create_by(name: "Nebraska")
State.find_or_create_by(name: "Nevada")
State.find_or_create_by(name: "New Hampshire")
State.find_or_create_by(name: "New Jersey")
State.find_or_create_by(name: "New Mexico")
State.find_or_create_by(name: "New York")
State.find_or_create_by(name: "North Carolina")
State.find_or_create_by(name: "North Dakota")
State.find_or_create_by(name: "Ohio")
State.find_or_create_by(name: "Oklahoma")
State.find_or_create_by(name: "Oregon")
State.find_or_create_by(name: "Pennsylvania")
State.find_or_create_by(name: "Puerto Rico")
State.find_or_create_by(name: "Rhode Island")
State.find_or_create_by(name: "South Carolina")
State.find_or_create_by(name: "South Dakota")
State.find_or_create_by(name: "Tennessee")
State.find_or_create_by(name: "Texas")
State.find_or_create_by(name: "Utah")
State.find_or_create_by(name: "Vermont")
State.find_or_create_by(name: "Virginia")
State.find_or_create_by(name: "Washington")
State.find_or_create_by(name: "West Virginia")
State.find_or_create_by(name: "Wisconsin")
State.find_or_create_by(name: "Wyoming")

# Colleges
College.find_or_create_by(name: "University of Akron", mascot: "Zips", city: "Akron", state: State.find_or_create_by(name: "Ohio"), conference: Conference.find_or_create_by(name: "Mid-American Conference"))
College.find_or_create_by(name: "University of Alabama", mascot: "Crimson Tide", city: "Tuscaloosa", state: State.find_or_create_by(name: "Alabama"), conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "Alabama Agricultural and Mechanical University", mascot: "Bulldogs and Lady Bulldogs", city: "Huntsville", state: State.find_or_create_by(name: "Alabama"), conference: Conference.find_or_create_by(name: "Southwestern Athletic Conference"))
College.find_or_create_by(name: "University of Alabama at Birmingham", mascot: "Blazers", city: "Birmingham", state: State.find_or_create_by(name: "Alabama"), conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "Alabama State University", mascot: "Hornets and Lady Hornets", city: "Montgomery", state: State.find_or_create_by(name: "Alabama"), conference: Conference.find_or_create_by(name: "Southwestern Athletic Conference"))
College.find_or_create_by(name: "University at Albany, SUNY", mascot: "Great Danes", city: "Albany", state: State.find_or_create_by(name: "New York"), conference: Conference.find_or_create_by(name: "America East Conference"))
College.find_or_create_by(name: "Alcorn State University", mascot: "Braves and Lady Braves", city: "Lorman", state: State.find_or_create_by(name: "Mississippi"), conference: Conference.find_or_create_by(name: "Southwestern Athletic Conference"))
College.find_or_create_by(name: "American University", mascot: "Eagles", city: "Washington", state: State.find_or_create_by(name: "District of Columbia"), conference: Conference.find_or_create_by(name: "Patriot League"))
College.find_or_create_by(name: "Appalachian State University", mascot: "Mountaineers", city: "Boone", state: State.find_or_create_by(name: "North Carolina"), conference: Conference.find_or_create_by(name: "Southern Conference"))
College.find_or_create_by(name: "University of Arizona", mascot: "Wildcats", city: "Tucson", state: State.find_or_create_by(name: "Arizona"), conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
College.find_or_create_by(name: "Arizona State University", mascot: "Sun Devils", city: "Tempe", state: State.find_or_create_by(name: "Arizona"), conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
College.find_or_create_by(name: "University of Arkansas", mascot: "Razorbacks and Razorback women", city: "Fayetteville", state: State.find_or_create_by(name: "Arkansas"), conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "University of Arkansas at Little Rock", mascot: "Trojans", city: "Little Rock", state: State.find_or_create_by(name: "Arkansas"), conference: Conference.find_or_create_by(name: "Sun Belt Conference"))
College.find_or_create_by(name: "University of Arkansas at Pine Bluff", mascot: "Golden Lions", city: "Pine Bluff", state: State.find_or_create_by(name: "Arkansas"), conference: Conference.find_or_create_by(name: "Southwestern Athletic Conference"))
College.find_or_create_by(name: "Arkansas State University", mascot: "Red Wolves", city: "Jonesboro", state: State.find_or_create_by(name: "Arkansas"), conference: Conference.find_or_create_by(name: "Sun Belt Conference"))
College.find_or_create_by(name: "Auburn University", mascot: "Tigers", city: "Auburn", state: State.find_or_create_by(name: "Alabama"), conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "Austin Peay State University", mascot: "Governors and Lady Govs", city: "Clarksville", state: State.find_or_create_by(name: "Tennessee"), conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
College.find_or_create_by(name: "Ball State University", mascot: "Cardinals", city: "Muncie", state: State.find_or_create_by(name: "Indiana"), conference: Conference.find_or_create_by(name: "Mid-American Conference"))
College.find_or_create_by(name: "Baylor University", mascot: "Bears and Lady Bears", city: "Waco", state: State.find_or_create_by(name: "Texas"), conference: Conference.find_or_create_by(name: "Big 12 Conference"))
College.find_or_create_by(name: "Belmont University", mascot: "Bruins", city: "Nashville", state: State.find_or_create_by(name: "Tennessee"), conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
College.find_or_create_by(name: "Bethune-Cookman University", mascot: "Wildcats", city: "Daytona Beach", state: State.find_or_create_by(name: "Florida"), conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
College.find_or_create_by(name: "Binghamton University", mascot: "Bearcats", city: "Vestal", state: State.find_or_create_by(name: "New York"), conference: Conference.find_or_create_by(name: "America East Conference"))
College.find_or_create_by(name: "Boise State University", mascot: "Broncos", city: "Boise", state: State.find_or_create_by(name: "Idaho"), conference: Conference.find_or_create_by(name: "Mountain West Conference"))
College.find_or_create_by(name: "Boston College", mascot: "Eagles", city: "Chestnut Hill", state: State.find_or_create_by(name: "Massachusetts"), conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
College.find_or_create_by(name: "Boston University", mascot: "Terriers", city: "Boston", state: State.find_or_create_by(name: "Massachusetts"), conference: Conference.find_or_create_by(name: "Patriot League"))
College.find_or_create_by(name: "Bowling Green State University", mascot: "Falcons", city: "Bowling Green", state: State.find_or_create_by(name: "Ohio"), conference: Conference.find_or_create_by(name: "Mid-American Conference"))
College.find_or_create_by(name: "Bradley University", mascot: "Braves", city: "Peoria", state: State.find_or_create_by(name: "Illinois"), conference: Conference.find_or_create_by(name: "Missouri Valley Conference"))
College.find_or_create_by(name: "Brigham Young University", mascot: "Cougars", city: "Provo", state: State.find_or_create_by(name: "Utah"), conference: Conference.find_or_create_by(name: "West Coast Conference"))
College.find_or_create_by(name: "Brown University", mascot: "Bears", city: "Providence", state: State.find_or_create_by(name: "Rhode Island"), conference: Conference.find_or_create_by(name: "Ivy League"))
College.find_or_create_by(name: "Bryant University", mascot: "Bulldogs", city: "Smithfield", state: State.find_or_create_by(name: "Rhode Island"), conference: Conference.find_or_create_by(name: "Northeast Conference"))
College.find_or_create_by(name: "Bucknell University", mascot: "Bison", city: "Lewisburg", state: State.find_or_create_by(name: "Pennsylvania"), conference: Conference.find_or_create_by(name: "Patriot League"))
College.find_or_create_by(name: "University at Buffalo, SUNY", mascot: "Bulls", city: "Buffalo", state: State.find_or_create_by(name: "New York"), conference: Conference.find_or_create_by(name: "Mid-American Conference"))
College.find_or_create_by(name: "Butler University", mascot: "Bulldogs", city: "Indianapolis", state: State.find_or_create_by(name: "Indiana"), conference: Conference.find_or_create_by(name: "Big East Conference"))
College.find_or_create_by(name: "University of California, Berkeley", mascot: "Golden Bears", city: "Berkeley", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
College.find_or_create_by(name: "University of California, Davis", mascot: "Aggies", city: "Davis", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Big West Conference"))
College.find_or_create_by(name: "University of California, Irvine", mascot: "Anteaters", city: "Irvine", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Big West Conference"))
College.find_or_create_by(name: "University of California, Los Angeles", mascot: "Bruins", city: "Los Angeles", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
College.find_or_create_by(name: "California Polytechnic State University", mascot: "Mustangs", city: "San Luis Obispo", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Big West Conference"))
College.find_or_create_by(name: "University of California, Riverside", mascot: "Highlanders", city: "Riverside", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Big West Conference"))
College.find_or_create_by(name: "University of California, Santa Barbara", mascot: "Gauchos", city: "Santa Barbara", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Big West Conference"))
College.find_or_create_by(name: "California State University, Bakersfield", mascot: "Roadrunners", city: "Bakersfield", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Western Athletic Conference"))
College.find_or_create_by(name: "California State University, Fresno", mascot: "Bulldogs", city: "Fresno", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Mountain West Conference"))
College.find_or_create_by(name: "California State University, Fullerton", mascot: "Titans", city: "Fullerton", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Big West Conference"))
College.find_or_create_by(name: "California State University, Long Beach", mascot: "49ers", city: "Long Beach", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Big West Conference"))
College.find_or_create_by(name: "California State University, Northridge", mascot: "Matadors", city: "Northridge", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Big West Conference"))
College.find_or_create_by(name: "California State University, Sacramento", mascot: "Hornets", city: "Sacramento", state: State.find_or_create_by(name: "California"), conference: Conference.find_or_create_by(name: "Big Sky Conference"))
College.find_or_create_by(name: "Campbell University", mascot: "Fighting Camels and Lady Camels", city: "Buies Creek", state: State.find_or_create_by(name: "North Carolina"), conference: Conference.find_or_create_by(name: "Big South Conference"))
College.find_or_create_by(name: "Canisius College", mascot: "Griffins", city: "Buffalo", state: State.find_or_create_by(name: "New York"), conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
College.find_or_create_by(name: "University of Central Arkansas", mascot: "Bears and Sugar Bears", city: "Conway", state: State.find_or_create_by(name: "Arkansas"), conference: Conference.find_or_create_by(name: "Southland Conference"))
College.find_or_create_by(name: "Central Connecticut State University", mascot: "Blue Devils", city: "New Britain", state: State.find_or_create_by(name: "Connecticut"), conference: Conference.find_or_create_by(name: "Northeast Conference"))
College.find_or_create_by(name: "University of Central Florida", mascot: "Knights", city: "Orlando", state: State.find_or_create_by(name: "Florida"), conference: Conference.find_or_create_by(name: "American Athletic Conference"))
College.find_or_create_by(name: "Central Michigan University", mascot: "Chippewas", city: "Mount Pleasant", state: State.find_or_create_by(name: "Michigan"), conference: Conference.find_or_create_by(name: "Mid-American Conference"))
College.find_or_create_by(name: "College of Charleston", mascot: "Cougars", city: "Charleston", state: State.find_or_create_by(name: "South Carolina"), conference: Conference.find_or_create_by(name: "Colonial Athletic Association"))
College.find_or_create_by(name: "Charleston Southern University", mascot: "Buccaneers and Lady Bucs", city: "Charleston", state: State.find_or_create_by(name: "South Carolina"), conference: Conference.find_or_create_by(name: "Big South Conference"))
College.find_or_create_by(name: "Chicago State University", mascot: "Cougars", city: "Chicago", state: State.find_or_create_by(name: "Illinois"), conference: Conference.find_or_create_by(name: "Western Athletic Conference"))
College.find_or_create_by(name: "University of Cincinnati", mascot: "Bearcats", city: "Cincinnati ", state: State.find_or_create_by(name: "Ohio"), conference: Conference.find_or_create_by(name: "American Athletic Conference"))
College.find_or_create_by(name: "The Citadel", mascot: "Bulldogs", city: "Charleston", state: State.find_or_create_by(name: "South Carolina"), conference: Conference.find_or_create_by(name: "Southern Conference"))
College.find_or_create_by(name: "Clemson University", mascot: "Tigers", city: "Clemson", state: State.find_or_create_by(name: "South Carolina"), conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
College.find_or_create_by(name: "Cleveland State University", mascot: "Vikings", city: "Cleveland", state: State.find_or_create_by(name: "Ohio"), conference: Conference.find_or_create_by(name: "Horizon League"))
College.find_or_create_by(name: "Coastal Carolina University", mascot: "Chanticleers  Conway", state: State.find_or_create_by(name: "South Carolina"), conference: Conference.find_or_create_by(name: "Big South Conference"))
College.find_or_create_by(name: "Colgate University", mascot: "Raiders", city: "Hamilton", state: State.find_or_create_by(name: "New York"), conference: Conference.find_or_create_by(name: "Patriot League"))
College.find_or_create_by(name: "University of Colorado at Boulder", mascot: "Buffaloes", city: "Boulder", state: State.find_or_create_by(name: "Colorado"), conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
College.find_or_create_by(name: "Colorado State University", mascot: "Rams", city: "Fort Collins", state: State.find_or_create_by(name: "Colorado"), conference: Conference.find_or_create_by(name: "Mountain West Conference"))
College.find_or_create_by(name: "Columbia University", mascot: "Lions", city: "Manhattan", state: State.find_or_create_by(name: "New York"), conference: Conference.find_or_create_by(name: "Ivy League"))
College.find_or_create_by(name: "University of Connecticut", mascot: "Huskies", city: "Storrs", state: State.find_or_create_by(name: "Connecticut"), conference: Conference.find_or_create_by(name: "American Athletic Conference"))
College.find_or_create_by(name: "Coppin State University", mascot: "Eagles", city: "Baltimore", state: State.find_or_create_by(name: "Maryland"), conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
College.find_or_create_by(name: "Cornell University", mascot: "Big Red", city: "Ithaca", state: State.find_or_create_by(name: "New York"), conference: Conference.find_or_create_by(name: "Ivy League"))
College.find_or_create_by(name: "Creighton University", mascot: "Bluejays", city: "Omaha", state: State.find_or_create_by(name: "Nebraska"), conference: Conference.find_or_create_by(name: "Big East Conference"))
College.find_or_create_by(name: "Dartmouth College", mascot: "Big Green", city: "Hanover", state: State.find_or_create_by(name: "New Hampshire"), conference: Conference.find_or_create_by(name: "Ivy League"))
College.find_or_create_by(name: "Davidson College", mascot: "Wildcats", city: "Davidson", state: State.find_or_create_by(name: "North Carolina"), conference: Conference.find_or_create_by(name: "Southern Conference"))
College.find_or_create_by(name: "University of Dayton", mascot: "Flyers", city: "Dayton", state: State.find_or_create_by(name: "Ohio"), conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
College.find_or_create_by(name: "University of Delaware", mascot: "Fightin' Blue Hens", city: "Newark", state: State.find_or_create_by(name: "Delaware"), conference: Conference.find_or_create_by(name: "Colonial Athletic Association"))
College.find_or_create_by(name: "Delaware State University", mascot: "Hornets and Lady Hornets", city: "Dover", state: State.find_or_create_by(name: "Delaware"), conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
College.find_or_create_by(name: "University of Denver", mascot: "Pioneers", city: "Denver", state: State.find_or_create_by(name: "Colorado"), conference: Conference.find_or_create_by(name: "The Summit League"))
College.find_or_create_by(name: "DePaul University", mascot: "Blue Demons", city: "Chicago", state: State.find_or_create_by(name: "Illinois"), conference: Conference.find_or_create_by(name: "Big East Conference"))
College.find_or_create_by(name: "University of Detroit Mercy", mascot: "Titans", city: "Detroit", state: State.find_or_create_by(name: "Michigan"), conference: Conference.find_or_create_by(name: "Horizon League"))
College.find_or_create_by(name: "Drake University", mascot: "Bulldogs", city: "Des Moines", state: State.find_or_create_by(name: "Iowa"), conference: Conference.find_or_create_by(name: "Missouri Valley Conference"))
College.find_or_create_by(name: "Drexel University", mascot: "Dragons", city: "Philadelphia", state: State.find_or_create_by(name: "Pennsylvania"), conference: Conference.find_or_create_by(name: "Colonial Athletic Association"))
College.find_or_create_by(name: "Duke University", mascot: "Blue Devils", city: "Durham", state: State.find_or_create_by(name: "North Carolina"), conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
College.find_or_create_by(name: "Duquesne University", mascot: "Dukes", city: "Pittsburgh", state: State.find_or_create_by(name: "Pennsylvania"), conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
College.find_or_create_by(name: "East Carolina University", mascot: "Pirates and Lady Pirates", city: "Greenville", state: State.find_or_create_by(name: "North Carolina"), conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "East Tennessee State University", mascot: "Buccaneers and Lady Bucs", city: "Johnson City", state: State.find_or_create_by(name: "Tennessee"), conference: Conference.find_or_create_by(name: "Atlantic Sun Conference"))
College.find_or_create_by(name: "Eastern Illinois University", mascot: "Panthers", city: "Charleston", state: State.find_or_create_by(name: "Illinois"), conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
College.find_or_create_by(name: "Eastern Kentucky University", mascot: "Colonels and Lady Colonels", city: "Richmond", state: State.find_or_create_by(name: "Kentucky"), conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
College.find_or_create_by(name: "Eastern Michigan University", mascot: "Eagles", city: "Ypsilanti", state: State.find_or_create_by(name: "Michigan"), conference: Conference.find_or_create_by(name: "Mid-American Conference"))
College.find_or_create_by(name: "Eastern Washington University", mascot: "Eagles", city: "Cheney", state: State.find_or_create_by(name: "Washington", conference: Conference.find_or_create_by(name: "Big Sky Conference"))
College.find_or_create_by(name: "Elon University", mascot: "Phoenix", city: "Elon", state: State.find_or_create_by(name: "North Carolina", conference: Conference.find_or_create_by(name: "Southern Conference"))
College.find_or_create_by(name: "University of Evansville", mascot: "Purple Aces", city: "Evansville", state: State.find_or_create_by(name: "Indiana", conference: Conference.find_or_create_by(name: "Missouri Valley Conference"))
College.find_or_create_by(name: "Fairfield University", mascot: "Stags", city: "Fairfield", state: State.find_or_create_by(name: "Connecticut", conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
College.find_or_create_by(name: "Fairleigh Dickinson University", mascot: "Knights", city: "Hackensack", state: State.find_or_create_by(name: "New Jersey", conference: Conference.find_or_create_by(name: "Northeast Conference"))
College.find_or_create_by(name: "University of Florida", mascot: "Gators", city: "Gainesville", state: State.find_or_create_by(name: "Florida", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "Florida A&M University", mascot: "Rattlers and Lady Rattlers", city: "Tallahassee", state: State.find_or_create_by(name: "Florida", conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
College.find_or_create_by(name: "Florida Atlantic University", mascot: "Owls", city: "Boca Raton", state: State.find_or_create_by(name: "Florida", conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "Florida Gulf Coast University", mascot: "Eagles", city: "Fort Myers", state: State.find_or_create_by(name: "Florida", conference: Conference.find_or_create_by(name: "Atlantic Sun Conference"))
College.find_or_create_by(name: "Florida International University", mascot: "Panthers", city: "Miami", state: State.find_or_create_by(name: "Florida", conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "Florida State University", mascot: "Seminoles", city: "Tallahassee", state: State.find_or_create_by(name: "Florida", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
College.find_or_create_by(name: "Fordham University", mascot: "Rams", city: "Bronx", state: State.find_or_create_by(name: "New York", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
College.find_or_create_by(name: "Furman University", mascot: "Paladins and Lady Paladins", city: "Greenville", state: State.find_or_create_by(name: "South Carolina", conference: Conference.find_or_create_by(name: "Southern Conference"))
College.find_or_create_by(name: "Gardner–Webb University", mascot: "Runnin' Bulldogs", city: "Boiling Springs", state: State.find_or_create_by(name: "North Carolina", conference: Conference.find_or_create_by(name: "Big South Conference"))
College.find_or_create_by(name: "George Mason University", mascot: "Patriots", city: "Fairfax", state: State.find_or_create_by(name: "Virginia", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
College.find_or_create_by(name: "George Washington University", mascot: "Colonials", city: "Washington", state: State.find_or_create_by(name: "District of Columbia", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
College.find_or_create_by(name: "Georgetown University", mascot: "Hoyas", city: "Washington", state: State.find_or_create_by(name: "District of Columbia", conference: Conference.find_or_create_by(name: "Big East Conference"))
College.find_or_create_by(name: "University of Georgia", mascot: "Bulldogs and Lady Bulldogs", city: "Athens", state: State.find_or_create_by(name: "Georgia", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "Georgia Institute of Technology", mascot: "Yellow Jackets", city: "Atlanta", state: State.find_or_create_by(name: "Georgia", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
College.find_or_create_by(name: "Georgia Southern University", mascot: "Eagles and Lady Eagles", city: "Statesboro", state: State.find_or_create_by(name: "Georgia", conference: Conference.find_or_create_by(name: "Southern Conference[A 1]"))
College.find_or_create_by(name: "Georgia State University", mascot: "Panthers", city: "Atlanta", state: State.find_or_create_by(name: "Georgia", conference: Conference.find_or_create_by(name: "Sun Belt Conference"))
College.find_or_create_by(name: "Gonzaga University", mascot: "Bulldogs", city: "Spokane", state: State.find_or_create_by(name: "Washington", conference: Conference.find_or_create_by(name: "West Coast Conference"))
College.find_or_create_by(name: "Grambling State University", mascot: "Tigers and Lady Tigers", city: "Grambling", state: State.find_or_create_by(name: "Louisiana", conference: Conference.find_or_create_by(name: "Southwestern Athletic Conference"))
College.find_or_create_by(name: "Hampton University", mascot: "Pirates and Lady Pirates", city: "Hampton", state: State.find_or_create_by(name: "Virginia", conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
College.find_or_create_by(name: "University of Hartford", mascot: "Hawks", city: "West Hartford", state: State.find_or_create_by(name: "Connecticut", conference: Conference.find_or_create_by(name: "America East Conference"))
College.find_or_create_by(name: "Harvard University", mascot: "Crimson", city: "Cambridge", state: State.find_or_create_by(name: "Massachusetts", conference: Conference.find_or_create_by(name: "Ivy League"))
College.find_or_create_by(name: "University of Hawaiʻi at Mānoa", mascot: "Rainbow Warriors and Rainbow Wahine", city: "Honolulu", state: State.find_or_create_by(name: "Hawaii", conference: Conference.find_or_create_by(name: "Big West Conference"))
College.find_or_create_by(name: "High Point University", mascot: "Panthers", city: "High Point", state: State.find_or_create_by(name: "North Carolina", conference: Conference.find_or_create_by(name: "Big South Conference"))
College.find_or_create_by(name: "Hofstra University", mascot: "Pride", city: "Hempstead", state: State.find_or_create_by(name: "New York", conference: Conference.find_or_create_by(name: "Colonial Athletic Association"))
College.find_or_create_by(name: "College of the Holy Cross", mascot: "Crusaders", city: "Worcester", state: State.find_or_create_by(name: "Massachusetts", conference: Conference.find_or_create_by(name: "Patriot League"))
College.find_or_create_by(name: "University of Houston", mascot: "Cougars", city: "Houston", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "American Athletic Conference"))
College.find_or_create_by(name: "Houston Baptist University", mascot: "Huskies", city: "Houston", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Southland Conference"))
College.find_or_create_by(name: "Howard University", mascot: "Bison and Lady Bison", city: "Washington", state: State.find_or_create_by(name: "District of Columbia", conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
College.find_or_create_by(name: "University of Idaho", mascot: "Vandals", city: "Moscow", state: State.find_or_create_by(name: "Idaho", conference: Conference.find_or_create_by(name: "Western Athletic Conference"))
College.find_or_create_by(name: "Idaho State University", mascot: "Bengals", city: "Pocatello", state: State.find_or_create_by(name: "Idaho", conference: Conference.find_or_create_by(name: "Big Sky Conference"))
College.find_or_create_by(name: "University of Illinois at Chicago", mascot: "Flames", city: "Chicago", state: State.find_or_create_by(name: "Illinois", conference: Conference.find_or_create_by(name: "Horizon League"))
College.find_or_create_by(name: "Illinois State University", mascot: "Redbirds", city: "Normal", state: State.find_or_create_by(name: "Illinois", conference: Conference.find_or_create_by(name: "Missouri Valley Conference"))
College.find_or_create_by(name: "University of Illinois at Urbana–Champaign", mascot: "Fighting Illini", city: "Urbana–Champaign", state: State.find_or_create_by(name: "Illinois", conference: Conference.find_or_create_by(name: "Big Ten Conference"))
College.find_or_create_by(name: "Indiana State University", mascot: "Sycamores", city: "Terre Haute", state: State.find_or_create_by(name: "Indiana", conference: Conference.find_or_create_by(name: "Missouri Valley Conference"))
College.find_or_create_by(name: "Indiana University", mascot: "Hoosiers", city: "Bloomington", state: State.find_or_create_by(name: "Indiana", conference: Conference.find_or_create_by(name: "Big Ten Conference"))
College.find_or_create_by(name: "Indiana University – Purdue University Fort Wayne", mascot: "Mastodons", city: "Fort Wayne", state: State.find_or_create_by(name: "Indiana", conference: Conference.find_or_create_by(name: "The Summit League"))
College.find_or_create_by(name: "Indiana University – Purdue University Indianapolis", mascot: "Jaguars", city: "Indianapolis", state: State.find_or_create_by(name: "Indiana", conference: Conference.find_or_create_by(name: "The Summit League"))
College.find_or_create_by(name: "Iona College", mascot: "Gaels", city: "New Rochelle", state: State.find_or_create_by(name: "New York", conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
College.find_or_create_by(name: "University of Iowa", mascot: "Hawkeyes", city: "Iowa City", state: State.find_or_create_by(name: "Iowa", conference: Conference.find_or_create_by(name: "Big Ten Conference"))
College.find_or_create_by(name: "Iowa State University", mascot: "Cyclones", city: "Ames", state: State.find_or_create_by(name: "Iowa", conference: Conference.find_or_create_by(name: "Big 12 Conference"))
College.find_or_create_by(name: "Jackson State University", mascot: "Tigers and Lady Tigers", city: "Jackson", state: State.find_or_create_by(name: "Mississippi", conference: Conference.find_or_create_by(name: "Southwestern Athletic Conference"))
College.find_or_create_by(name: "Jacksonville University", mascot: "Dolphins", city: "Jacksonville", state: State.find_or_create_by(name: "Florida", conference: Conference.find_or_create_by(name: "Atlantic Sun Conference"))
College.find_or_create_by(name: "Jacksonville State University", mascot: "Gamecocks", city: "Jacksonville", state: State.find_or_create_by(name: "Alabama", conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
College.find_or_create_by(name: "James Madison University", mascot: "Dukes", city: "Harrisonburg", state: State.find_or_create_by(name: "Virginia", conference: Conference.find_or_create_by(name: "Colonial Athletic Association"))
College.find_or_create_by(name: "University of Kansas", mascot: "Jayhawks", city: "Lawrence", state: State.find_or_create_by(name: "Kansas", conference: Conference.find_or_create_by(name: "Big 12 Conference"))
College.find_or_create_by(name: "Kansas State University", mascot: "Wildcats", city: "Manhattan", state: State.find_or_create_by(name: "Kansas", conference: Conference.find_or_create_by(name: "Big 12 Conference"))
College.find_or_create_by(name: "Kennesaw State University", mascot: "Owls and Lady Owls", city: "Kennesaw", state: State.find_or_create_by(name: "Georgia", conference: Conference.find_or_create_by(name: "Atlantic Sun Conference"))
College.find_or_create_by(name: "Kent State University", mascot: "Golden Flashes", city: "Kent", state: State.find_or_create_by(name: "Ohio", conference: Conference.find_or_create_by(name: "Mid-American Conference"))
College.find_or_create_by(name: "University of Kentucky", mascot: "Wildcats", city: "Lexington", state: State.find_or_create_by(name: "Kentucky", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "La Salle University", mascot: "Explorers", city: "Philadelphia", state: State.find_or_create_by(name: "Pennsylvania", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
College.find_or_create_by(name: "Lafayette College", mascot: "Leopards", city: "Easton", state: State.find_or_create_by(name: "Pennsylvania", conference: Conference.find_or_create_by(name: "Patriot League"))
College.find_or_create_by(name: "Lamar University", mascot: "Cardinals and Lady Cardinals", city: "Beaumont", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Southland Conference"))
College.find_or_create_by(name: "Lehigh University", mascot: "Mountain Hawks", city: "Bethlehem", state: State.find_or_create_by(name: "Pennsylvania", conference: Conference.find_or_create_by(name: "Patriot League"))
College.find_or_create_by(name: "Liberty University", mascot: "Flames and Lady Flames", city: "Lynchburg", state: State.find_or_create_by(name: "Virginia", conference: Conference.find_or_create_by(name: "Big South Conference"))
College.find_or_create_by(name: "Lipscomb University", mascot: "Bisons and Lady Bisons", city: "Nashville", state: State.find_or_create_by(name: "Tennessee", conference: Conference.find_or_create_by(name: "Atlantic Sun Conference"))
College.find_or_create_by(name: "Long Island University–Brooklyn", mascot: "Blackbirds", city: "Brooklyn", state: State.find_or_create_by(name: "New York", conference: Conference.find_or_create_by(name: "Northeast Conference"))
College.find_or_create_by(name: "Longwood University", mascot: "Lancers", city: "Farmville", state: State.find_or_create_by(name: "Virginia", conference: Conference.find_or_create_by(name: "Big South Conference"))
College.find_or_create_by(name: "University of Louisiana at Lafayette", mascot: "Ragin' Cajuns", city: "Lafayette", state: State.find_or_create_by(name: "Louisiana", conference: Conference.find_or_create_by(name: "Sun Belt Conference"))
College.find_or_create_by(name: "University of Louisiana at Monroe", mascot: "Warhawks", city: "Monroe", state: State.find_or_create_by(name: "Louisiana", conference: Conference.find_or_create_by(name: "Sun Belt Conference"))
College.find_or_create_by(name: "Louisiana State University", mascot: "Tigers and Lady Tigers", city: "Baton Rouge", state: State.find_or_create_by(name: "Louisiana", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "Louisiana Tech University", mascot: "Bulldogs and Lady Techsters", city: "Ruston", state: State.find_or_create_by(name: "Louisiana", conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "University of Louisville", mascot: "Cardinals", city: "Louisville", state: State.find_or_create_by(name: "Kentucky", conference: Conference.find_or_create_by(name: "American Athletic Conference"))
College.find_or_create_by(name: "Loyola Marymount University", mascot: "Lions", city: "Los Angeles", state: State.find_or_create_by(name: "California", conference: Conference.find_or_create_by(name: "West Coast Conference"))
College.find_or_create_by(name: "Loyola University Chicago", mascot: "Ramblers", city: "Chicago", state: State.find_or_create_by(name: "Illinois", conference: Conference.find_or_create_by(name: "Missouri Valley Conference"))
College.find_or_create_by(name: "Loyola University Maryland", mascot: "Greyhounds", city: "Baltimore", state: State.find_or_create_by(name: "Maryland", conference: Conference.find_or_create_by(name: "Patriot League"))
College.find_or_create_by(name: "University of Maine", mascot: "Black Bears", city: "Orono", state: State.find_or_create_by(name: "Maine", conference: Conference.find_or_create_by(name: "America East Conference"))
College.find_or_create_by(name: "Manhattan College", mascot: "Jaspers and Lady Jaspers", city: "Riverdale", state: State.find_or_create_by(name: "New York", conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
College.find_or_create_by(name: "Marist College", mascot: "Red Foxes", city: "Poughkeepsie", state: State.find_or_create_by(name: "New York", conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
College.find_or_create_by(name: "Marquette University", mascot: "Golden Eagles", city: "Milwaukee", state: State.find_or_create_by(name: "Wisconsin", conference: Conference.find_or_create_by(name: "Big East Conference"))
College.find_or_create_by(name: "Marshall University", mascot: "Thundering Herd", city: "Huntington", state: State.find_or_create_by(name: "West Virginia", conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "University of Maryland, Baltimore County", mascot: "Retrievers", city: "Catonsville", state: State.find_or_create_by(name: "Maryland", conference: Conference.find_or_create_by(name: "America East Conference"))
College.find_or_create_by(name: "University of Maryland, College Park", mascot: "Terrapins", city: "College Park", state: State.find_or_create_by(name: "Maryland", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
College.find_or_create_by(name: "University of Maryland Eastern Shore", mascot: "Hawks and Lady Hawks", city: "Princess Anne", state: State.find_or_create_by(name: "Maryland", conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
College.find_or_create_by(name: "University of Massachusetts Amherst", mascot: "Minutemen and Minutewomen", city: "Amherst", state: State.find_or_create_by(name: "Massachusetts", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
College.find_or_create_by(name: "McNeese State University", mascot: "Cowboys and Cowgirls", city: "Lake Charles", state: State.find_or_create_by(name: "Louisiana", conference: Conference.find_or_create_by(name: "Southland Conference"))
College.find_or_create_by(name: "University of Memphis", mascot: "Tigers and Lady Tigers", city: "Memphis", state: State.find_or_create_by(name: "Tennessee", conference: Conference.find_or_create_by(name: "American Athletic Conference"))
College.find_or_create_by(name: "Mercer University", mascot: "Bears", city: "Macon Georgia", conference: Conference.find_or_create_by(name: "Atlantic Sun Conference"))
College.find_or_create_by(name: "University of Miami", mascot: "Hurricanes", city: "Coral Gables", state: State.find_or_create_by(name: "Florida", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
College.find_or_create_by(name: "Miami University", mascot: "RedHawks", city: "Oxford", state: State.find_or_create_by(name: "Ohio", conference: Conference.find_or_create_by(name: "Mid-American Conference"))
College.find_or_create_by(name: "University of Michigan", mascot: "Wolverines", city: "Ann Arbor", state: State.find_or_create_by(name: "Michigan"), conference: Conference.find_or_create_by(name: "Big Ten Conference"))
College.find_or_create_by(name: "Michigan State University", mascot: "Spartans", city: "East Lansing", state: State.find_or_create_by(name: "Michigan"), conference: Conference.find_or_create_by(name: "Big Ten Conference"))
College.find_or_create_by(name: "Middle Tennessee State University", mascot: "Blue Raiders", city: "Murfreesboro  Tennessee", conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "University of Minnesota", mascot: "Golden Gophers", city: "Minneapolis–Saint Paul", state: State.find_or_create_by(name: "Minnesota", conference: Conference.find_or_create_by(name: "Big Ten Conference"))
College.find_or_create_by(name: "University of Mississippi", mascot: "Rebels", city: "Oxford", state: State.find_or_create_by(name: "Mississippi", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "Mississippi State University", mascot: "Bulldogs", city: "Starkville", state: State.find_or_create_by(name: "Mississippi", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "Mississippi Valley State University", mascot: "Delta Devils and Devilettes", city: "Itta Bena", state: State.find_or_create_by(name: "Mississippi", conference: Conference.find_or_create_by(name: "Southwestern Athletic Conference"))
College.find_or_create_by(name: "University of Missouri", mascot: "Tigers", city: "Columbia", state: State.find_or_create_by(name: "Missouri", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "University of Missouri–Kansas City", mascot: "Kangaroos", city: "Kansas City", state: State.find_or_create_by(name: "Missouri", conference: Conference.find_or_create_by(name: "Western Athletic Conference"))
College.find_or_create_by(name: "Missouri State University", mascot: "Bears and Lady Bears", city: "Springfield", state: State.find_or_create_by(name: "Missouri", conference: Conference.find_or_create_by(name: "Missouri Valley Conference"))
College.find_or_create_by(name: "Monmouth University", mascot: "Hawks", city: "West Long Branch", state: State.find_or_create_by(name: "New Jersey", conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
College.find_or_create_by(name: "University of Montana", mascot: "Grizzlies", city: "Missoula", state: State.find_or_create_by(name: "Montana", conference: Conference.find_or_create_by(name: "Big Sky Conference"))
College.find_or_create_by(name: "Montana State University", mascot: "Bobcats", city: "Bozeman", state: State.find_or_create_by(name: "Montana", conference: Conference.find_or_create_by(name: "Big Sky Conference"))
College.find_or_create_by(name: "Morehead State University", mascot: "Eagles", city: "Morehead", state: State.find_or_create_by(name: "Kentucky", conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
College.find_or_create_by(name: "Morgan State University", mascot: "Bears and Lady Bears", city: "Baltimore", state: State.find_or_create_by(name: "Maryland", conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
College.find_or_create_by(name: "Mount St. Mary's University", mascot: "Mountaineer", city: "Emmitsburg", state: State.find_or_create_by(name: "Maryland", conference: Conference.find_or_create_by(name: "Northeast Conference"))
College.find_or_create_by(name: "Murray State University", mascot: "Racers and Lady Racers", city: "Murray", state: State.find_or_create_by(name: "Kentucky", conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
College.find_or_create_by(name: "University of Nebraska–Lincoln", mascot: "Cornhuskers", city: "Lincoln", state: State.find_or_create_by(name: "Nebraska", conference: Conference.find_or_create_by(name: "Big Ten Conference"))
College.find_or_create_by(name: "University of Nevada, Las Vegas", mascot: "Rebels", city: "Paradise", state: State.find_or_create_by(name: "Nevada", conference: Conference.find_or_create_by(name: "Mountain West Conference"))
College.find_or_create_by(name: "University of Nevada, Reno", mascot: "Wolf Pack", city: "Reno", state: State.find_or_create_by(name: "Nevada", conference: Conference.find_or_create_by(name: "Mountain West Conference"))
College.find_or_create_by(name: "University of New Hampshire", mascot: "Wildcats", city: "Durham", state: State.find_or_create_by(name: "New Hampshire", conference: Conference.find_or_create_by(name: "America East Conference"))
College.find_or_create_by(name: "New Jersey Institute of Technology", mascot: "Highlanders", city: "Newark", state: State.find_or_create_by(name: "New Jersey", conference: Conference.find_or_create_by(name: "Great West Conference"))
College.find_or_create_by(name: "University of New Mexico", mascot: "Lobos", city: "Albuquerque", state: State.find_or_create_by(name: "New Mexico", conference: Conference.find_or_create_by(name: "Mountain West Conference"))
College.find_or_create_by(name: "New Mexico State University", mascot: "Aggies", city: "Las Cruces  New Mexico", conference: Conference.find_or_create_by(name: "Western Athletic Conference"))
College.find_or_create_by(name: "University of New Orleans", mascot: "Privateers", city: "New Orleans Louisiana", conference: Conference.find_or_create_by(name: "Southland Conference"))
# College.find_or_create_by(name: "Niagara University", mascot: "Purple Eagles", city: "Lewiston  New York", conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
# College.find_or_create_by(name: "Nicholls State University", mascot: "Colonels Thibodaux Louisiana", conference: Conference.find_or_create_by(name: "Southland Conference"))
# College.find_or_create_by(name: "Norfolk State University", mascot: "Spartans  Norfolk Virginia", conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
# College.find_or_create_by(name: "North Carolina Agricultural and Technical State University", mascot: "Aggies Greensboro  North Carolina", conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
# College.find_or_create_by(name: "University of North Carolina at Asheville", mascot: "Bulldogs  Asheville North Carolina", conference: Conference.find_or_create_by(name: "Big South Conference"))
# College.find_or_create_by(name: "North Carolina Central University", mascot: "Eagles Durham  North Carolina", conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
# College.find_or_create_by(name: "University of North Carolina at Chapel Hill", mascot: "Tar Heels  Chapel Hill North Carolina", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
# College.find_or_create_by(name: "University of North Carolina at Charlotte", mascot: "49ers Charlotte North Carolina", conference: Conference.find_or_create_by(name: "Conference USA"))
# College.find_or_create_by(name: "University of North Carolina at Greensboro", mascot: "Spartans Greensboro  North Carolina", conference: Conference.find_or_create_by(name: "Southern Conference"))
# College.find_or_create_by(name: "North Carolina State University", mascot: "Wolfpack Raleigh North Carolina", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
# College.find_or_create_by(name: "University of North Carolina Wilmington", mascot: "Seahawks Wilmington  North Carolina", conference: Conference.find_or_create_by(name: "Colonial Athletic Association"))
# College.find_or_create_by(name: "University of North Dakota", mascot: "Fighting Sioux Grand Forks North Dakota", conference: Conference.find_or_create_by(name: "Big Sky Conference"))
# College.find_or_create_by(name: "North Dakota State University", mascot: "Bison  Fargo North Dakota", conference: Conference.find_or_create_by(name: "The Summit League"))
# College.find_or_create_by(name: "University of North Florida", mascot: "Ospreys and Lady Ospreys  Jacksonville", conference: Conference.find_or_create_by(name: "Florida Atlantic Sun Conference"))
# College.find_or_create_by(name: "University of North Texas", mascot: "Mean Green  Denton  Texas", conference: Conference.find_or_create_by(name: "Conference USA"))
# College.find_or_create_by(name: "Northeastern University", mascot: "Huskies  Boston  Massachusetts", conference: Conference.find_or_create_by(name: "Colonial Athletic Association"))
# College.find_or_create_by(name: "Northern Arizona University", mascot: "Arizona Lumberjacks  Flagstaff Arizona", conference: Conference.find_or_create_by(name: "Big Sky Conference"))
# College.find_or_create_by(name: "University of Northern Colorado", mascot: "Bears Greeley Colorado", conference: Conference.find_or_create_by(name: "Big Sky Conference"))
# College.find_or_create_by(name: "Northern Illinois University", mascot: "Huskies DeKalb  Illinois", conference: Conference.find_or_create_by(name: "Mid-American Conference"))
# College.find_or_create_by(name: "University of Northern", mascot: "Iowa Panthers  Cedar Falls Iowa", conference: Conference.find_or_create_by(name: "Missouri Valley Conference"))
# College.find_or_create_by(name: "Northwestern State University", mascot: "Demons and Lady Demons Natchitoches  Louisiana", conference: Conference.find_or_create_by(name: "Southland Conference"))
# College.find_or_create_by(name: "Northwestern University", mascot: "Wildcats Evanston  Illinois", conference: Conference.find_or_create_by(name: "Big Ten Conference"))
# College.find_or_create_by(name: "University of Notre Dame", mascot: "Fighting Irish South Bend  Indiana", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
# College.find_or_create_by(name: "Oakland University", mascot: "Golden Grizzlies  Rochester Michigan", conference: Conference.find_or_create_by(name: "Horizon League"))
# College.find_or_create_by(name: "Ohio University", mascot: "Bobcats  Athens  Ohio", conference: Conference.find_or_create_by(name: "Mid-American Conference"))
# College.find_or_create_by(name: "Ohio State University", mascot: "Buckeyes Columbus  Ohio", conference: Conference.find_or_create_by(name: "Big Ten Conference"))
# College.find_or_create_by(name: "University of Oklahoma", mascot: "Sooners  Norman  Oklahoma", conference: Conference.find_or_create_by(name: "Big 12 Conference"))
# College.find_or_create_by(name: "Oklahoma State University–Stillwater", mascot: "Cowboys and Cowgirls Stillwater  Oklahoma", conference: Conference.find_or_create_by(name: "Big 12 Conference"))
# College.find_or_create_by(name: "Old Dominion University", mascot: "Monarchs and Lady Monarchs Norfolk Virginia", conference: Conference.find_or_create_by(name: "Conference USA"))
# College.find_or_create_by(name: "Oral Roberts University", mascot: "Golden Eagles  Tulsa Oklahoma", conference: Conference.find_or_create_by(name: "Southland Conference"))
# College.find_or_create_by(name: "University of Oregon", mascot: "Ducks  Eugene  Oregon", conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
# College.find_or_create_by(name: "Oregon State University", mascot: "Beavers  Corvallis Oregon", conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
# College.find_or_create_by(name: "University of the Pacific", mascot: "Tigers  Stockton  California", conference: Conference.find_or_create_by(name: "West Coast Conference"))
# College.find_or_create_by(name: "University of Pennsylvania", mascot: "Quakers  Philadelphia  Pennsylvania", conference: Conference.find_or_create_by(name: "Ivy League"))
# College.find_or_create_by(name: "Pennsylvania State University", mascot: "Nittany Lions[A 25]  State College Pennsylvania", conference: Conference.find_or_create_by(name: "Big Ten Conference"))
# College.find_or_create_by(name: "Pepperdine University", mascot: "Waves  Malibu  California", conference: Conference.find_or_create_by(name: "West Coast Conference"))
# College.find_or_create_by(name: "University of Pittsburgh", mascot: "Panthers Pittsburgh  Pennsylvania", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
# College.find_or_create_by(name: "University of Portland", mascot: "Pilots Portland  Oregon", conference: Conference.find_or_create_by(name: "West Coast Conference"))
# College.find_or_create_by(name: "Portland State University", mascot: "Vikings  Portland  Oregon", conference: Conference.find_or_create_by(name: "Big Sky Conference"))
# College.find_or_create_by(name: "Prairie View A&M University", mascot: "Panthers and Lady Panthers Prairie View  Texas", conference: Conference.find_or_create_by(name: "Southwestern Athletic Conference"))
# College.find_or_create_by(name: "Presbyterian College", mascot: "Blue Hose  Clinton South Carolina", conference: Conference.find_or_create_by(name: "Big South Conference"))
# College.find_or_create_by(name: "Princeton University", mascot: "Tigers  Princeton New Jersey", conference: Conference.find_or_create_by(name: "Ivy League"))
# College.find_or_create_by(name: "Providence College  Providence Friars Providence  Rhode Island", conference: Conference.find_or_create_by(name: "Big East Conference"))
# College.find_or_create_by(name: "Purdue University Purdue Boilermakers West Lafayette  Indiana", conference: Conference.find_or_create_by(name: "Big Ten Conference"))
# College.find_or_create_by(name: "Quinnipiac University Quinnipiac Bobcats  Hamden  Connecticut", conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
# College.find_or_create_by(name: "Radford University  Radford Highlanders Radford Virginia", conference: Conference.find_or_create_by(name: "Big South Conference"))
# College.find_or_create_by(name: "University of Rhode Island  Rhode Island Rams Kingston  Rhode Island", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
# College.find_or_create_by(name: "Rice University Rice Owls Houston Texas", conference: Conference.find_or_create_by(name: "Conference USA"))
# College.find_or_create_by(name: "University of Richmond  Richmond Spiders  Richmond  Virginia", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
# College.find_or_create_by(name: "Rider University  Rider Broncs  Lawrenceville New Jersey", conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
# College.find_or_create_by(name: "Robert Morris University  Robert Morris Colonials Moon Township Pennsylvania", conference: Conference.find_or_create_by(name: "Northeast Conference"))
# College.find_or_create_by(name: "Rutgers University  Rutgers Scarlet Knights New Brunswick New Jersey", conference: Conference.find_or_create_by(name: "American Athletic Conference"))
# College.find_or_create_by(name: "Sacred Heart University Sacred Heart Pioneers Fairfield Connecticut", conference: Conference.find_or_create_by(name: "Northeast Conference"))
# College.find_or_create_by(name: "St. Bonaventure University  St. Bonaventure Bonnies St. Bonaventure New York", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
# College.find_or_create_by(name: "St. Francis College St. Francis Terriers[A 28]  Brooklyn  New York", conference: Conference.find_or_create_by(name: "Northeast Conference"))
# College.find_or_create_by(name: "Saint Francis University  Saint Francis Red Flash[A 29] Loretto Pennsylvania", conference: Conference.find_or_create_by(name: "Northeast Conference"))
# College.find_or_create_by(name: "St. John's University St. John's Red Storm[A 30]  Jamaica New York", conference: Conference.find_or_create_by(name: "Big East Conference"))
# College.find_or_create_by(name: "Saint Joseph's University Saint Joseph's Hawks[A 31]  Philadelphia  Pennsylvania", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
# College.find_or_create_by(name: "Saint Louis University  Saint Louis Billikens St. Louis Missouri", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
# College.find_or_create_by(name: "Saint Mary's College of California  Saint Mary's Gaels  Moraga  California", conference: Conference.find_or_create_by(name: "West Coast Conference"))
# College.find_or_create_by(name: "Saint Peter's University  Saint Peter's Peacocks and Peahens  Jersey City New Jersey", conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
# College.find_or_create_by(name: "Sam Houston State University  Sam Houston State Bearkats  Huntsville  Texas", conference: Conference.find_or_create_by(name: "Southland Conference"))
# College.find_or_create_by(name: "Samford University  Samford Bulldogs  Homewood  Alabama", conference: Conference.find_or_create_by(name: "Southern Conference"))
# College.find_or_create_by(name: "University of San Diego San Diego Toreros San Diego California", conference: Conference.find_or_create_by(name: "West Coast Conference"))
# College.find_or_create_by(name: "San Diego State University  San Diego State Aztecs  San Diego California", conference: Conference.find_or_create_by(name: "Mountain West Conference"))
# College.find_or_create_by(name: "University of San Francisco San Francisco Dons  San Francisco California", conference: Conference.find_or_create_by(name: "West Coast Conference"))
# College.find_or_create_by(name: "San Jose State University San Jose State Spartans San Jose  California", conference: Conference.find_or_create_by(name: "Mountain West Conference"))
# College.find_or_create_by(name: "Santa Clara University  Santa Clara Broncos Santa Clara California", conference: Conference.find_or_create_by(name: "West Coast Conference"))
# College.find_or_create_by(name: "Savannah State University Savannah State Tigers and Lady Tigers Savannah  Georgia", conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
# College.find_or_create_by(name: "Seattle University  Seattle Redhawks  Seattle Washington", conference: Conference.find_or_create_by(name: "Western Athletic Conference"))
# College.find_or_create_by(name: "Seton Hall University Seton Hall Pirates  South Orange  New Jersey", conference: Conference.find_or_create_by(name: "Big East Conference"))
# College.find_or_create_by(name: "Siena College Siena Saints  Loudonville New York", conference: Conference.find_or_create_by(name: "Metro Atlantic Athletic Conference"))
# College.find_or_create_by(name: "University of South Alabama South Alabama Jaguars Mobile  Alabama", conference: Conference.find_or_create_by(name: "Sun Belt Conference"))
# College.find_or_create_by(name: "University of South Carolina  South Carolina Gamecocks  Columbia  South Carolina", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
# College.find_or_create_by(name: "South Carolina State University South Carolina State Bulldogs and Lady Bulldogs Orangeburg  South Carolina", conference: Conference.find_or_create_by(name: "Mid-Eastern Athletic Conference"))
# College.find_or_create_by(name: "University of South Carolina Upstate  South Carolina Upstate Spartans Spartanburg South Carolina", conference: Conference.find_or_create_by(name: "Atlantic Sun Conference"))
# College.find_or_create_by(name: "University of South Dakota  South Dakota Coyotes  Vermillion  South Dakota", conference: Conference.find_or_create_by(name: "The Summit League"))
# College.find_or_create_by(name: "South Dakota State University South Dakota State Jackrabbits  Brookings South Dakota", conference: Conference.find_or_create_by(name: "The Summit League"))
# College.find_or_create_by(name: "University of South Florida South Florida Bulls Tampa Florida", conference: Conference.find_or_create_by(name: "American Athletic Conference"))
# College.find_or_create_by(name: "Southeast Missouri State University Southeast Missouri Redhawks Cape Girardeau  Missouri", conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
# College.find_or_create_by(name: "Southeastern Louisiana University Southeastern Louisiana Lions and Lady Lions Hammond Louisiana", conference: Conference.find_or_create_by(name: "Southland Conference"))
# College.find_or_create_by(name: "University of Southern California USC Trojans[A 33][A 34] Los Angeles California", conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
# College.find_or_create_by(name: "Southern Illinois University Carbondale Southern Illinois Salukis Carbondale  Illinois", conference: Conference.find_or_create_by(name: "Missouri Valley Conference"))
# College.find_or_create_by(name: "Southern Illinois University Edwardsville SIU Edwardsville Cougars[A 35]  Edwardsville  Illinois", conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
# College.find_or_create_by(name: "Southern Methodist University SMU Mustangs  University Park Texas", conference: Conference.find_or_create_by(name: "American Athletic Conference"))
# College.find_or_create_by(name: "University of Southern Mississippi  Southern Miss Golden Eagles Hattiesburg Mississippi", conference: Conference.find_or_create_by(name: "Conference USA"))
# College.find_or_create_by(name: "Southern University Southern Jaguars and Lady Jaguars Baton Rouge Louisiana", conference: Conference.find_or_create_by(name: "Southwestern Athletic Conference"))
# College.find_or_create_by(name: "Southern Utah University  Southern Utah Thunderbirds and Lady Thunderbirds  Cedar City  Utah", conference: Conference.find_or_create_by(name: "Big Sky Conference"))
# College.find_or_create_by(name: "Stanford University Stanford Cardinal Palo Alto California", conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
# College.find_or_create_by(name: "Stephen F. Austin State University  Stephen F. Austin Lumberjacks and Ladyjacks Nacogdoches Texas", conference: Conference.find_or_create_by(name: "Southland Conference"))
# College.find_or_create_by(name: "Stetson University  Stetson Hatters DeLand  Florida", conference: Conference.find_or_create_by(name: "Atlantic Sun Conference"))
# College.find_or_create_by(name: "Stony Brook University  Stony Brook Seawolves Stony Brook New York", conference: Conference.find_or_create_by(name: "America East Conference"))
# College.find_or_create_by(name: "Syracuse University Syracuse Orange Syracuse  New York", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
# College.find_or_create_by(name: "Temple University Temple Owls Philadelphia  Pennsylvania", conference: Conference.find_or_create_by(name: "American Athletic Conference"))
# College.find_or_create_by(name: "University of Tennessee Tennessee Volunteers and Lady Vols[A 36]  Knoxville Tennessee", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
# College.find_or_create_by(name: "University of Tennessee at Chattanooga  Chattanooga Mocs and Lady Mocs  Chattanooga Tennessee", conference: Conference.find_or_create_by(name: "Southern Conference"))
# College.find_or_create_by(name: "University of Tennessee at Martin Tennessee–Martin Skyhawks Martin  Tennessee", conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
# College.find_or_create_by(name: "Tennessee State University  Tennessee State Tigers and Lady Tigers  Nashville Tennessee", conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
# College.find_or_create_by(name: "Tennessee Technological University  Tennessee Tech Golden Eagles  Cookeville  Tennessee", conference: Conference.find_or_create_by(name: "Ohio Valley Conference"))
College.find_or_create_by(name: "Texas A&M University  Texas A&M Aggies  College Station", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "Texas A&M University–Corpus Christi Texas A&M–Corpus Christi Islanders  Corpus Christi", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Southland Conference"))
College.find_or_create_by(name: "University of Texas at Arlington", mascot: "Mavericks", city: "Arlington", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Sun Belt Conference"))
College.find_or_create_by(name: "University of Texas at Austin", mascot: "Longhorns", city: "Austin", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Big 12 Conference"))
College.find_or_create_by(name: "Texas Christian University", mascot: "Horned Frogs and Lady Frogs", city: "Fort Worth", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Big 12 Conference"))
College.find_or_create_by(name: "University of Texas at El Paso", mascot: "Miners", city: "El Paso", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "University of Texas–Pan American", mascot: "Broncs and Lady Broncs", city: "Edinburg", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Western Athletic Conference"))
College.find_or_create_by(name: "University of Texas at San Antonio", mascot: "Roadrunners", city: "San Antonio", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "Texas Southern University", mascot: "Tigers and Lady Tigers", city: "Houston", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Southwestern Athletic Conference"))
College.find_or_create_by(name: "Texas State University", mascot: "Bobcats", city: "San Marcos", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Sun Belt Conference"))
College.find_or_create_by(name: "Texas Tech University", mascot: "Red Raiders", city: "Lubbock", state: State.find_or_create_by(name: "Texas", conference: Conference.find_or_create_by(name: "Big 12 Conference"))
College.find_or_create_by(name: "University of Toledo", mascot: "Rockets", city: "Toledo", state: State.find_or_create_by(name: "Ohio", conference: Conference.find_or_create_by(name: "Mid-American Conference"))
College.find_or_create_by(name: "Towson University", mascot: "Tigers", city: "Towson", state: State.find_or_create_by(name: "Maryland", conference: Conference.find_or_create_by(name: "Colonial Athletic Association"))
College.find_or_create_by(name: "Troy University", mascot: "Trojans", city: "Troy", state: State.find_or_create_by(name: "Alabama", conference: Conference.find_or_create_by(name: "Sun Belt Conference"))
College.find_or_create_by(name: "Tulane University", mascot: "Green Wave", city: "New Orleans", state: State.find_or_create_by(name: "Louisiana", conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "University of Tulsa", mascot: "Golden Hurricane", city: "Tulsa", state: State.find_or_create_by(name: "Oklahoma", conference: Conference.find_or_create_by(name: "Conference USA"))
College.find_or_create_by(name: "United States Air Force Academy", mascot: "Falcons", city: "Colorado Springs", state: State.find_or_create_by(name: "Colorado", conference: Conference.find_or_create_by(name: "Mountain West Conference"))
College.find_or_create_by(name: "United States Military Academy", mascot: "Black Knights", city: "West Point", state: State.find_or_create_by(name: "New York", conference: Conference.find_or_create_by(name: "Patriot League"))
College.find_or_create_by(name: "United States Naval Academy", mascot: "Midshipmen", city: "Annapolis", state: State.find_or_create_by(name: "Maryland", conference: Conference.find_or_create_by(name: "Patriot League"))
College.find_or_create_by(name: "University of Utah", mascot: "Utes", city: "Salt Lake City", state: State.find_or_create_by(name: "Utah", conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
College.find_or_create_by(name: "Utah State University", mascot: "Aggies", city: "Logan", state: State.find_or_create_by(name: "Utah", conference: Conference.find_or_create_by(name: "Mountain West Conference"))
College.find_or_create_by(name: "Utah Valley University", mascot: "Wolverines", city: "Orem", state: State.find_or_create_by(name: "Utah", conference: Conference.find_or_create_by(name: "Western Athletic Conference"))
College.find_or_create_by(name: "Valparaiso University", mascot: "Crusaders", city: "Valparaiso", state: State.find_or_create_by(name: "Indiana", conference: Conference.find_or_create_by(name: "Horizon League"))
College.find_or_create_by(name: "Vanderbilt University", mascot: "Commodores", city: "Nashville", state: State.find_or_create_by(name: "Tennessee", conference: Conference.find_or_create_by(name: "Southeastern Conference"))
College.find_or_create_by(name: "University of Vermont", mascot: "Catamounts", city: "Burlington", state: State.find_or_create_by(name: "Vermont", conference: Conference.find_or_create_by(name: "America East Conference"))
College.find_or_create_by(name: "Villanova University", mascot: "Wildcats", city: "Radnor Township", state: State.find_or_create_by(name: "Pennsylvania", conference: Conference.find_or_create_by(name: "Big East Conference"))
College.find_or_create_by(name: "University of Virginia", mascot: "Cavaliers", city: "Charlottesville", state: State.find_or_create_by(name: "Virginia", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
College.find_or_create_by(name: "Virginia Commonwealth University", mascot: "Rams", city: "Richmond", state: State.find_or_create_by(name: "Virginia", conference: Conference.find_or_create_by(name: "Atlantic 10 Conference"))
College.find_or_create_by(name: "Virginia Military Institute", mascot: "Keydets", city: "Lexington", state: State.find_or_create_by(name: "Virginia", conference: Conference.find_or_create_by(name: "Big South Conference"))
College.find_or_create_by(name: "Virginia Tech", mascot: "Hokies", city: "Blacksburg", state: State.find_or_create_by(name: "Virginia", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
College.find_or_create_by(name: "Wagner College", mascot: "Seahawks", city: "Staten Island", state: State.find_or_create_by(name: "New York", conference: Conference.find_or_create_by(name: "Northeast Conference"))
College.find_or_create_by(name: "Wake Forest University", mascot: "Demon Deacons", city: "Winston-Salem", state: State.find_or_create_by(name: "North Carolina", conference: Conference.find_or_create_by(name: "Atlantic Coast Conference"))
College.find_or_create_by(name: "University of Washington", mascot: "Huskies", city: "Seattle", state: State.find_or_create_by(name: "Washington", conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
College.find_or_create_by(name: "Washington State University", mascot: "Cougars", city: "Pullman", state: State.find_or_create_by(name: "Washington", conference: Conference.find_or_create_by(name: "Pacific-12 Conference"))
College.find_or_create_by(name: "Weber State University", mascot: "Wildcats", city: "Ogden", state: State.find_or_create_by(name: "Utah", conference: Conference.find_or_create_by(name: "Big Sky Conference"))
College.find_or_create_by(name: "West Virginia University", mascot: "Mountaineers", city: "Morgantown", state: State.find_or_create_by(name: "West Virginia", conference: Conference.find_or_create_by(name: "Big 12 Conference"))
College.find_or_create_by(name: "Western Carolina University", mascot: "Catamounts", city: "Cullowhee", state: State.find_or_create_by(name: "North Carolina", conference: Conference.find_or_create_by(name: "Southern Conference"))
College.find_or_create_by(name: "Western Illinois University", mascot: "Leathernecks", city: "Macomb", state: State.find_or_create_by(name: "Illinois", conference: Conference.find_or_create_by(name: "The Summit League"))
College.find_or_create_by(name: "Western Kentucky University", mascot: "Hilltoppers and Lady Toppers", city: "Bowling Green", state: State.find_or_create_by(name: "Kentucky", conference: Conference.find_or_create_by(name: "Sun Belt Conference"))
College.find_or_create_by(name: "Western Michigan University", mascot: "Broncos", city: "Kalamazoo", state: State.find_or_create_by(name: "Michigan", conference: Conference.find_or_create_by(name: "Mid-American Conference"))
College.find_or_create_by(name: "Wichita State University", mascot: "Shockers", city: "Wichita", state: State.find_or_create_by(name: "Kansas", conference: Conference.find_or_create_by(name: "Missouri Valley Conference"))
College.find_or_create_by(name: "College of William & Mary", mascot: "Tribe", city: "Williamsburg", state: State.find_or_create_by(name: "Virginia", conference: Conference.find_or_create_by(name: "Colonial Athletic Association"))
College.find_or_create_by(name: "Winthrop University", mascot: "Eagles", city: "Rock Hill", state: State.find_or_create_by(name: "South Carolina", conference: Conference.find_or_create_by(name: "Big South Conference"))
College.find_or_create_by(name: "University of Wisconsin–Green Bay", mascot: "Phoenix", city: "Green Bay", state: State.find_or_create_by(name: "Wisconsin", conference: Conference.find_or_create_by(name: "Horizon League"))
College.find_or_create_by(name: "University of Wisconsin–Madison", mascot: "Badgers", city: "Madison", state: State.find_or_create_by(name: "Wisconsin", conference: Conference.find_or_create_by(name: "Big Ten Conference"))
College.find_or_create_by(name: "University of Wisconsin–Milwaukee", mascot: "Panthers", city: "Milwaukee", state: State.find_or_create_by(name: "Wisconsin", conference: Conference.find_or_create_by(name: "Horizon League"))
College.find_or_create_by(name: "Wofford College", mascot: "Terriers", city: "Spartanburg", state: State.find_or_create_by(name: "South Carolina"), conference: Conference.find_or_create_by(name: "Southern Conference"))
College.find_or_create_by(name: "Wright State University", mascot: "Raiders", city: "Fairborn", state: State.find_or_create_by(name: "Ohio"), conference: Conference.find_or_create_by(name: "Horizon League"))
College.find_or_create_by(name: "University of Wyoming", mascot: "Cowboys and Cowgirls", city: "Laramie", state: State.find_or_create_by(name: "Wyoming"), conference: Conference.find_or_create_by(name: "Mountain West Conference"))
College.find_or_create_by(name: "Xavier University", mascot: "Musketeers", city: "Cincinnati", state: State.find_or_create_by(name: "Ohio"), conference: Conference.find_or_create_by(name: "Big East Conference"))
College.find_or_create_by(name: "Yale University", mascot: "Bulldogs", city: "New Haven", state: State.find_or_create_by(name: "Connecticut"), conference: Conference.find_or_create_by(name: "Ivy League"))
College.find_or_create_by(name: "Youngstown State University", mascot: "Penguins", city: "Youngstown", state: State.find_or_create_by(name: "Ohio"), conference: Conference.find_or_create_by(name: "Horizon League"))

