# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: " 'Chicago' }, { name: " 'Copenhagen' }])
#   Mayor.create(name: " 'Emanuel', city: cities.first)

College.find_or_create_by(name: "University of Akron", mascot: "Zips", city: "Akron", state: "Ohio", conference: "Mid-American Conference")
College.find_or_create_by(name: "University of Alabama", mascot: "Crimson Tide", city: "Tuscaloosa", state: "Alabama", conference: "Southeastern Conference")
College.find_or_create_by(name: "Alabama Agricultural and Mechanical University", mascot: "Bulldogs and Lady Bulldogs", city: "Huntsville", state: "Alabama", conference: "Southwestern Athletic Conference")
College.find_or_create_by(name: "University of Alabama at Birmingham", mascot: "Blazers", city: "Birmingham", state: "Alabama", conference: "Conference USA")
College.find_or_create_by(name: "Alabama State University", mascot: "Hornets and Lady Hornets", city: "Montgomery", state: "Alabama", conference: "Southwestern Athletic Conference")
College.find_or_create_by(name: "University at Albany, SUNY", mascot: "Great Danes", city: "Albany", state: "New York", conference: "America East Conference")
College.find_or_create_by(name: "Alcorn State University", mascot: "Braves and Lady Braves", city: "Lorman", state: "Mississippi", conference: "Southwestern Athletic Conference")
College.find_or_create_by(name: "American University", mascot: "Eagles", city: "Washington", state: "District of Columbia", conference: "Patriot League")
College.find_or_create_by(name: "Appalachian State University", mascot: "Mountaineers", city: "Boone North Carolina", conference: "Southern Conference")
College.find_or_create_by(name: "University of Arizona", mascot: "Wildcats", city: "Tucson", state: "Arizona", conference: "Pacific-12 Conference")
College.find_or_create_by(name: "Arizona State University", mascot: "Sun Devils", city: "Tempe", state: "Arizona", conference: "Pacific-12 Conference")
College.find_or_create_by(name: "University of Arkansas", mascot: "Razorbacks and Razorback women", city: "Fayetteville", state: "Arkansas", conference: "Southeastern Conference")
College.find_or_create_by(name: "University of Arkansas at Little Rock", mascot: "Trojans", city: "Little Rock", state: "Arkansas", conference: "Sun Belt Conference")
College.find_or_create_by(name: "University of Arkansas at Pine Bluff", mascot: "Golden Lions", city: "Pine Bluff", state: "Arkansas", conference: "Southwestern Athletic Conference")
College.find_or_create_by(name: "Arkansas State University", mascot: "Red Wolves", city: "Jonesboro", state: "Arkansas", conference: "Sun Belt Conference")
College.find_or_create_by(name: "Auburn University", mascot: "Tigers", city: "Auburn", state: "Alabama", conference: "Southeastern Conference")
College.find_or_create_by(name: "Austin Peay State University", mascot: "Governors and Lady Govs", city: "Clarksville", state: "Tennessee", conference: "Ohio Valley Conference")
College.find_or_create_by(name: "Ball State University", mascot: "Cardinals", city: "Muncie", state: "Indiana", conference: "Mid-American Conference")
College.find_or_create_by(name: "Baylor University", mascot: "Bears and Lady Bears", city: "Waco", state: "Texas", conference: "Big 12 Conference")
College.find_or_create_by(name: "Belmont University", mascot: "Bruins", city: "Nashville", state: "Tennessee", conference: "Ohio Valley Conference")
College.find_or_create_by(name: "Bethune-Cookman University", mascot: "Wildcats", city: "Daytona Beach", state: "Florida", conference: "Mid-Eastern Athletic Conference")
College.find_or_create_by(name: "Binghamton University", mascot: "Bearcats", city: "Vestal", state: "New York", conference: "America East Conference")
College.find_or_create_by(name: "Boise State University", mascot: "Broncos", city: "Boise", state: "Idaho", conference: "Mountain West Conference")
College.find_or_create_by(name: "Boston College", mascot: "Eagles", city: "Chestnut Hill", state: "Massachusetts", conference: "Atlantic Coast Conference")
College.find_or_create_by(name: "Boston University", mascot: "Terriers", city: "Boston", state: "Massachusetts", conference: "Patriot League")
College.find_or_create_by(name: "Bowling Green State University", mascot: "Falcons", city: "Bowling Green", state: "Ohio", conference: "Mid-American Conference")
College.find_or_create_by(name: "Bradley University", mascot: "Braves", city: "Peoria", state: "Illinois", conference: "Missouri Valley Conference")
College.find_or_create_by(name: "Brigham Young University", mascot: "Cougars", city: "Provo", state: "Utah", conference: "West Coast Conference")
College.find_or_create_by(name: "Brown University", mascot: "Bears", city: "Providence", state: "Rhode Island", conference: "Ivy League")
College.find_or_create_by(name: "Bryant University", mascot: "Bulldogs", city: "Smithfield", state: "Rhode Island", conference: "Northeast Conference")
College.find_or_create_by(name: "Bucknell University", mascot: "Bison", city: "Lewisburg", state: "Pennsylvania", conference: "Patriot League")
College.find_or_create_by(name: "University at Buffalo, SUNY", mascot: "Bulls", city: "Buffalo", state: "New York", conference: "Mid-American Conference")
College.find_or_create_by(name: "Butler University", mascot: "Bulldogs", city: "Indianapolis", state: "Indiana", conference: "Big East Conference")
College.find_or_create_by(name: "University of California, Berkeley", mascot: "Golden Bears", city: "Berkeley", state: "California", conference: "Pacific-12 Conference")
College.find_or_create_by(name: "University of California, Davis", mascot: "Aggies", city: "Davis", state: "California", conference: "Big West Conference")
College.find_or_create_by(name: "University of California, Irvine", mascot: "Anteaters", city: "Irvine", state: "California", conference: "Big West Conference")
College.find_or_create_by(name: "University of California, Los Angeles", mascot: "Bruins", city: "Los Angeles", state: "California", conference: "Pacific-12 Conference")
College.find_or_create_by(name: "California Polytechnic State University", mascot: "Mustangs", city: "San Luis Obispo", state: "California", conference: "Big West Conference")
College.find_or_create_by(name: "University of California, Riverside", mascot: "Highlanders", city: "Riverside", state: "California", conference: "Big West Conference")
College.find_or_create_by(name: "University of California, Santa Barbara", mascot: "Gauchos", city: "Santa Barbara", state: "California", conference: "Big West Conference")
College.find_or_create_by(name: "California State University, Bakersfield", mascot: "Roadrunners", city: "Bakersfield", state: "California", conference: "Western Athletic Conference")
College.find_or_create_by(name: "California State University, Fresno", mascot: "Bulldogs", city: "Fresno", state: "California", conference: "Mountain West Conference")
College.find_or_create_by(name: "California State University, Fullerton", mascot: "Titans", city: "Fullerton", state: "California", conference: "Big West Conference")
College.find_or_create_by(name: "California State University, Long Beach", mascot: "49ers", city: "Long Beach", state: "California", conference: "Big West Conference")
College.find_or_create_by(name: "California State University, Northridge", mascot: "Matadors", city: "Northridge", state: "California", conference: "Big West Conference")
College.find_or_create_by(name: "California State University, Sacramento", mascot: "Hornets", city: "Sacramento", state: "California", conference: "Big Sky Conference")
College.find_or_create_by(name: "Campbell University", mascot: "Fighting Camels and Lady Camels", city: "Buies Creek", state: "North Carolina", conference: "Big South Conference")
# College.find_or_create_by(name: "Canisius College", mascot: "Griffins  Buffalo New York  Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "University of Central Arkansas", mascot: "Bears and Sugar Bears Conway  Arkansas  Southland Conference")
# College.find_or_create_by(name: "Central Connecticut State University", mascot: "Blue Devils New Britain Connecticut Northeast Conference")
# College.find_or_create_by(name: "University of Central Florida", mascot: "Knights Orlando Florida American Athletic Conference")
# College.find_or_create_by(name: "Central Michigan University", mascot: "Chippewas Mount Pleasant  Michigan  Mid-American Conference")
# College.find_or_create_by(name: "College of Charleston", mascot: "Cougars Charleston  South Carolina  Colonial Athletic Association")
# College.find_or_create_by(name: "Charleston Southern University", mascot: "Buccaneers and Lady Bucs (golf) Charleston  South Carolina  Big South Conference")
# College.find_or_create_by(name: "Chicago State University", mascot: "Cougars Chicago Illinois  Western Athletic Conference")
# College.find_or_create_by(name: "University of Cincinnati", mascot: "Bearcats  Cincinnati  Ohio  American Athletic Conference")
# College.find_or_create_by(name: "The Citadel", mascot: "Bulldogs  Charleston  South Carolina  Southern Conference")
# College.find_or_create_by(name: "Clemson University", mascot: "Tigers  Clemson South Carolina  Atlantic Coast Conference")
# College.find_or_create_by(name: "Cleveland State University", mascot: "Vikings Cleveland Ohio  Horizon League")
# College.find_or_create_by(name: "Coastal Carolina University", mascot: "Chanticleers  Conway  South Carolina  Big South Conference")
# College.find_or_create_by(name: "Colgate University", mascot: "Raiders Hamilton  New York  Patriot League")
# College.find_or_create_by(name: "University of Colorado at Boulder", mascot: "Buffaloes Boulder Colorado  Pacific-12 Conference")
# College.find_or_create_by(name: "Colorado State University", mascot: "Rams  Fort Collins  Colorado  Mountain West Conference")
# College.find_or_create_by(name: "Columbia University", mascot: "Lions Manhattan New York  Ivy League")
# College.find_or_create_by(name: "University of Connecticut", mascot: "Huskies Storrs  Connecticut American Athletic Conference")
# College.find_or_create_by(name: "Coppin State University", mascot: "Eagles  Baltimore Maryland  Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "Cornell University", mascot: "Big Red Ithaca  New York  Ivy League")
# College.find_or_create_by(name: "Creighton University", mascot: "Bluejays  Omaha Nebraska  Big East Conference")
# College.find_or_create_by(name: "Dartmouth College", mascot: "Big Green Hanover New Hampshire Ivy League")
# College.find_or_create_by(name: "Davidson College", mascot: "Wildcats  Davidson  North Carolina  Southern Conference[A 4]")
# College.find_or_create_by(name: "University of Dayton", mascot: "Dayton Flyers Dayton  Ohio  Atlantic 10 Conference")
# College.find_or_create_by(name: "University of Delaware", mascot: "Fightin' Blue Hens  Newark  Delaware  Colonial Athletic Association")
# College.find_or_create_by(name: "Delaware State University", mascot: "Hornets and Lady Hornets  Dover Delaware  Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "University of Denver", mascot: "Pioneers  Denver  Colorado  The Summit League")
# College.find_or_create_by(name: "DePaul University", mascot: "Blue Demons Chicago Illinois  Big East Conference")
# College.find_or_create_by(name: "University of Detroit Mercy", mascot: "Titans  Detroit Michigan  Horizon League")
# College.find_or_create_by(name: "Drake University", mascot: "Bulldogs  Des Moines  Iowa  Missouri Valley Conference")
# College.find_or_create_by(name: "Drexel University", mascot: "Dragons Philadelphia  Pennsylvania  Colonial Athletic Association")
# College.find_or_create_by(name: "Duke University", mascot: "Blue Devils Durham  North Carolina  Atlantic Coast Conference")
# College.find_or_create_by(name: "Duquesne University", mascot: "Dukes Pittsburgh  Pennsylvania  Atlantic 10 Conference")
# College.find_or_create_by(name: "East Carolina University  East Carolina Pirates and Lady Pirates  Greenville  North Carolina  Conference USA[A 5]")
# College.find_or_create_by(name: "East Tennessee State University East Tennessee State Buccaneers and Lady Bucs Johnson City  Tennessee Atlantic Sun Conference[A 6]")
# College.find_or_create_by(name: "Eastern Illinois University Eastern Illinois Panthers Charleston  Illinois  Ohio Valley Conference")
# College.find_or_create_by(name: "Eastern Kentucky University Eastern Kentucky Colonels and Lady Colonels Richmond  Kentucky  Ohio Valley Conference")
# College.find_or_create_by(name: "Eastern Michigan University Eastern Michigan Eagles Ypsilanti Michigan  Mid-American Conference")
# College.find_or_create_by(name: "Eastern Washington University Eastern Washington Eagles Cheney  Washington  Big Sky Conference")
# College.find_or_create_by(name: "Elon University Elon Phoenix  Elon  North Carolina  Southern Conference[A 7]")
# College.find_or_create_by(name: "University of Evansville  Evansville Purple Aces  Evansville  Indiana Missouri Valley Conference")
# College.find_or_create_by(name: "Fairfield University  Fairfield Stags Fairfield Connecticut Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "Fairleigh Dickinson University  Fairleigh Dickinson Knights Hackensack  New Jersey  Northeast Conference")
# College.find_or_create_by(name: "University of Florida Florida Gators  Gainesville Florida Southeastern Conference")
# College.find_or_create_by(name: "Florida A&M University  Florida A&M Rattlers and Lady Rattlers  Tallahassee Florida Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "Florida Atlantic University Florida Atlantic Owls Boca Raton  Florida Conference USA")
# College.find_or_create_by(name: "Florida Gulf Coast University Florida Gulf Coast Eagles Fort Myers  Florida Atlantic Sun Conference")
# College.find_or_create_by(name: "Florida International University  FIU Panthers  Miami Florida Conference USA")
# College.find_or_create_by(name: "Florida State University  Florida State Seminoles Tallahassee Florida Atlantic Coast Conference")
# College.find_or_create_by(name: "Fordham University  Fordham Rams  Bronx New York  Atlantic 10 Conference")
# College.find_or_create_by(name: "Furman University Furman Paladins and Lady Paladins Greenville  South Carolina  Southern Conference")
# College.find_or_create_by(name: "Gardner–Webb University Gardner–Webb Runnin' Bulldogs Boiling Springs North Carolina  Big South Conference")
# College.find_or_create_by(name: "George Mason University George Mason Patriots Fairfax Virginia  Atlantic 10 Conference")
# College.find_or_create_by(name: "George Washington University  George Washington Colonials Washington  District of Columbia  Atlantic 10 Conference")
# College.find_or_create_by(name: "Georgetown University Georgetown Hoyas  Washington  District of Columbia  Big East Conference")
# College.find_or_create_by(name: "University of Georgia Georgia Bulldogs and Lady Bulldogs[A 8] Athens  Georgia Southeastern Conference")
# College.find_or_create_by(name: "Georgia Institute of Technology Georgia Tech Yellow Jackets Atlanta Georgia Atlantic Coast Conference")
# College.find_or_create_by(name: "Georgia Southern University Georgia Southern Eagles and Lady Eagles Statesboro  Georgia Southern Conference[A 1]")
# College.find_or_create_by(name: "Georgia State University  Georgia State Panthers  Atlanta Georgia Sun Belt Conference")
# College.find_or_create_by(name: "Gonzaga University  Gonzaga Bulldogs  Spokane Washington  West Coast Conference")
# College.find_or_create_by(name: "Grambling State University  Grambling State Tigers and Lady Tigers  Grambling Louisiana Southwestern Athletic Conference")
# College.find_or_create_by(name: "Hampton University  Hampton Pirates and Lady Pirates  Hampton Virginia  Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "University of Hartford  Hartford Hawks  West Hartford Connecticut America East Conference")
# College.find_or_create_by(name: "Harvard University  Harvard Crimson Cambridge[A 9]  Massachusetts Ivy League")
# College.find_or_create_by(name: "University of Hawaiʻi at Mānoa  Hawaiʻi Rainbow Warriors and Rainbow Wahine[A 10] Honolulu  Hawaii  Big West Conference")
# College.find_or_create_by(name: "High Point University High Point Panthers High Point  North Carolina  Big South Conference")
# College.find_or_create_by(name: "Hofstra University  Hofstra Pride Hempstead New York  Colonial Athletic Association")
# College.find_or_create_by(name: "College of the Holy Cross Holy Cross Crusaders  Worcester Massachusetts Patriot League")
# College.find_or_create_by(name: "University of Houston Houston Cougars Houston Texas American Athletic Conference")
# College.find_or_create_by(name: "Houston Baptist University  Houston Baptist Huskies Houston Texas Southland Conference")
# College.find_or_create_by(name: "Howard University Howard Bison and Lady Bison Washington  District of Columbia  Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "University of Idaho Idaho Vandals Moscow  Idaho Western Athletic Conference[A 11]")
# College.find_or_create_by(name: "Idaho State University  Idaho State Bengals Pocatello Idaho Big Sky Conference")
# College.find_or_create_by(name: "University of Illinois at Chicago UIC Flames[A 12]  Chicago Illinois  Horizon League")
# College.find_or_create_by(name: "Illinois State University Illinois State Redbirds Normal  Illinois  Missouri Valley Conference")
# College.find_or_create_by(name: "University of Illinois at Urbana–Champaign  Illinois Fighting Illini  Urbana–Champaign  Illinois  Big Ten Conference")
# College.find_or_create_by(name: "Indiana State University  Indiana State Sycamores Terre Haute Indiana Missouri Valley Conference")
# College.find_or_create_by(name: "Indiana University  Indiana Hoosiers  Bloomington Indiana Big Ten Conference")
# College.find_or_create_by(name: "Indiana University – Purdue University Fort Wayne IPFW Mastodons  Fort Wayne  Indiana The Summit League")
# College.find_or_create_by(name: "Indiana University – Purdue University Indianapolis IUPUI Jaguars Indianapolis  Indiana The Summit League")
# College.find_or_create_by(name: "Iona College  Iona Gaels  New Rochelle  New York  Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "University of Iowa  Iowa Hawkeyes Iowa City Iowa  Big Ten Conference")
# College.find_or_create_by(name: "Iowa State University Iowa State Cyclones Ames  Iowa  Big 12 Conference")
# College.find_or_create_by(name: "Jackson State University  Jackson State Tigers and Lady Tigers  Jackson Mississippi Southwestern Athletic Conference")
# College.find_or_create_by(name: "Jacksonville University Jacksonville Dolphins Jacksonville  Florida Atlantic Sun Conference")
# College.find_or_create_by(name: "Jacksonville State University Jacksonville State Gamecocks  Jacksonville  Alabama Ohio Valley Conference")
# College.find_or_create_by(name: "James Madison University  James Madison Dukes Harrisonburg  Virginia  Colonial Athletic Association")
# College.find_or_create_by(name: "University of Kansas  Kansas Jayhawks Lawrence  Kansas  Big 12 Conference")
# College.find_or_create_by(name: "Kansas State University Kansas State Wildcats Manhattan Kansas  Big 12 Conference")
# College.find_or_create_by(name: "Kennesaw State University Kennesaw State Owls and Lady Owls Kennesaw  Georgia Atlantic Sun Conference")
# College.find_or_create_by(name: "Kent State University Kent State Golden Flashes Kent  Ohio  Mid-American Conference")
# College.find_or_create_by(name: "University of Kentucky  Kentucky Wildcats Lexington Kentucky  Southeastern Conference")
# College.find_or_create_by(name: "La Salle University La Salle Explorers  Philadelphia  Pennsylvania  Atlantic 10 Conference")
# College.find_or_create_by(name: "Lafayette College Lafayette Leopards  Easton  Pennsylvania  Patriot League")
# College.find_or_create_by(name: "Lamar University  Lamar Cardinals and Lady Cardinals  Beaumont  Texas Southland Conference")
# College.find_or_create_by(name: "Lehigh University Lehigh Mountain Hawks Bethlehem Pennsylvania  Patriot League")
# College.find_or_create_by(name: "Liberty University  Liberty Flames and Lady Flames  Lynchburg Virginia  Big South Conference")
# College.find_or_create_by(name: "Lipscomb University Lipscomb Bisons and Lady Bisons Nashville Tennessee Atlantic Sun Conference")
# College.find_or_create_by(name: "Long Island University–Brooklyn Long Island Blackbirds  Brooklyn  New York  Northeast Conference")
# College.find_or_create_by(name: "Longwood University Longwood Lancers  Farmville Virginia  Big South Conference")
# College.find_or_create_by(name: "University of Louisiana at Lafayette  Louisiana–Lafayette Ragin' Cajuns Lafayette Louisiana Sun Belt Conference")
# College.find_or_create_by(name: "University of Louisiana at Monroe Louisiana–Monroe Warhawks Monroe  Louisiana Sun Belt Conference")
# College.find_or_create_by(name: "Louisiana State University  LSU Tigers and Lady Tigers  Baton Rouge Louisiana Southeastern Conference")
# College.find_or_create_by(name: "Louisiana Tech University Louisiana Tech Bulldogs and Lady Techsters  Ruston  Louisiana Conference USA")
# College.find_or_create_by(name: "University of Louisville  Louisville Cardinals  Louisville  Kentucky  American Athletic Conference[A 13]")
# College.find_or_create_by(name: "Loyola Marymount University Loyola Marymount Lions  Los Angeles California  West Coast Conference")
# College.find_or_create_by(name: "Loyola University Chicago Loyola Ramblers[A 14] Chicago Illinois  Missouri Valley Conference")
# College.find_or_create_by(name: "Loyola University Maryland  Loyola Greyhounds Baltimore Maryland  Patriot League")
# College.find_or_create_by(name: "University of Maine Maine Black Bears Orono Maine America East Conference")
# College.find_or_create_by(name: "Manhattan College Manhattan Jaspers and Lady Jaspers  Riverdale New York  Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "Marist College  Marist Red Foxes  Poughkeepsie  New York  Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "Marquette University  Marquette Golden Eagles Milwaukee Wisconsin Big East Conference")
# College.find_or_create_by(name: "Marshall University Marshall Thundering Herd  Huntington  West Virginia Conference USA")
# College.find_or_create_by(name: "University of Maryland, Baltimore County  UMBC Retrievers Catonsville Maryland  America East Conference")
# College.find_or_create_by(name: "University of Maryland, College Park  Maryland Terrapins  College Park  Maryland  Atlantic Coast Conference[A 15]")
# College.find_or_create_by(name: "University of Maryland Eastern Shore  UMES Hawks and Lady Hawks Princess Anne Maryland  Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "University of Massachusetts Amherst Massachusetts Minutemen and Minutewomen[A 16] Amherst Massachusetts Atlantic 10 Conference")
# College.find_or_create_by(name: "McNeese State University  McNeese State Cowboys and Cowgirls  Lake Charles  Louisiana Southland Conference")
# College.find_or_create_by(name: "University of Memphis Memphis Tigers and Lady Tigers  Memphis Tennessee American Athletic Conference")
# College.find_or_create_by(name: "Mercer University Mercer Bears  Macon Georgia Atlantic Sun Conference[A 6]")
# College.find_or_create_by(name: "University of Miami Miami Hurricanes[A 17]  Coral Gables  Florida Atlantic Coast Conference")
# College.find_or_create_by(name: "Miami University  Miami RedHawks[A 18]  Oxford  Ohio  Mid-American Conference")
# College.find_or_create_by(name: "University of Michigan  Michigan Wolverines Ann Arbor Michigan  Big Ten Conference")
# College.find_or_create_by(name: "Michigan State University Michigan State Spartans East Lansing  Michigan  Big Ten Conference")
# College.find_or_create_by(name: "Middle Tennessee State University Middle Tennessee Blue Raiders Murfreesboro  Tennessee Conference USA")
# College.find_or_create_by(name: "University of Minnesota Minnesota Golden Gophers  Minneapolis–Saint Paul  Minnesota Big Ten Conference")
# College.find_or_create_by(name: "University of Mississippi Ole Miss Rebels[A 19] Oxford  Mississippi Southeastern Conference")
# College.find_or_create_by(name: "Mississippi State University  Mississippi State Bulldogs  Starkville  Mississippi Southeastern Conference")
# College.find_or_create_by(name: "Mississippi Valley State University Mississippi Valley State Delta Devils and Devilettes  Itta Bena Mississippi Southwestern Athletic Conference")
# College.find_or_create_by(name: "University of Missouri  Missouri Tigers Columbia  Missouri  Southeastern Conference")
# College.find_or_create_by(name: "University of Missouri–Kansas City  UMKC Kangaroos  Kansas City Missouri  Western Athletic Conference")
# College.find_or_create_by(name: "Missouri State University Missouri State Bears and Lady Bears Springfield Missouri  Missouri Valley Conference")
# College.find_or_create_by(name: "Monmouth University Monmouth Hawks  West Long Branch  New Jersey  Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "University of Montana Montana Grizzlies[A 20] Missoula  Montana Big Sky Conference")
# College.find_or_create_by(name: "Montana State University  Montana State Bobcats Bozeman Montana Big Sky Conference")
# College.find_or_create_by(name: "Morehead State University Morehead State Eagles Morehead  Kentucky  Ohio Valley Conference")
# College.find_or_create_by(name: "Morgan State University Morgan State Bears and Lady Bears Baltimore Maryland  Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "Mount St. Mary's University Mount Saint Mary's Mountaineers Emmitsburg  Maryland  Northeast Conference")
# College.find_or_create_by(name: "Murray State University Murray State Racers and Lady Racers[A 21] Murray  Kentucky  Ohio Valley Conference")
# College.find_or_create_by(name: "University of Nebraska–Lincoln  Nebraska Cornhuskers  Lincoln Nebraska  Big Ten Conference")
# College.find_or_create_by(name: "University of Nevada, Las Vegas UNLV Rebels[A 22] Paradise  Nevada  Mountain West Conference")
# College.find_or_create_by(name: "University of Nevada, Reno  Nevada Wolf Pack  Reno  Nevada  Mountain West Conference")
# College.find_or_create_by(name: "University of New Hampshire New Hampshire Wildcats  Durham  New Hampshire America East Conference")
# College.find_or_create_by(name: "New Jersey Institute of Technology  NJIT Highlanders  Newark  New Jersey  Great West Conference[A 23]")
# College.find_or_create_by(name: "University of New Mexico  New Mexico Lobos  Albuquerque New Mexico  Mountain West Conference")
# College.find_or_create_by(name: "New Mexico State University New Mexico State Aggies Las Cruces  New Mexico  Western Athletic Conference")
# College.find_or_create_by(name: "University of New Orleans New Orleans Privateers  New Orleans Louisiana Southland Conference")
# College.find_or_create_by(name: "Niagara University  Niagara Purple Eagles Lewiston  New York  Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "Nicholls State University Nicholls State Colonels Thibodaux Louisiana Southland Conference")
# College.find_or_create_by(name: "Norfolk State University  Norfolk State Spartans  Norfolk Virginia  Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "North Carolina Agricultural and Technical State University  North Carolina A&T Aggies Greensboro  North Carolina  Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "University of North Carolina at Asheville UNC Asheville Bulldogs  Asheville North Carolina  Big South Conference")
# College.find_or_create_by(name: "North Carolina Central University North Carolina Central Eagles Durham  North Carolina  Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "University of North Carolina at Chapel Hill North Carolina Tar Heels  Chapel Hill North Carolina  Atlantic Coast Conference")
# College.find_or_create_by(name: "University of North Carolina at Charlotte Charlotte 49ers Charlotte North Carolina  Conference USA")
# College.find_or_create_by(name: "University of North Carolina at Greensboro  UNC Greensboro Spartans Greensboro  North Carolina  Southern Conference")
# College.find_or_create_by(name: "North Carolina State University NC State Wolfpack Raleigh North Carolina  Atlantic Coast Conference")
# College.find_or_create_by(name: "University of North Carolina Wilmington UNC Wilmington Seahawks Wilmington  North Carolina  Colonial Athletic Association")
# College.find_or_create_by(name: "University of North Dakota  North Dakota[A 24]  Grand Forks North Dakota  Big Sky Conference")
# College.find_or_create_by(name: "North Dakota State University North Dakota State Bison  Fargo North Dakota  The Summit League")
# College.find_or_create_by(name: "University of North Florida North Florida Ospreys and Lady Ospreys  Jacksonville  Florida Atlantic Sun Conference")
# College.find_or_create_by(name: "University of North Texas North Texas Mean Green  Denton  Texas Conference USA")
# College.find_or_create_by(name: "Northeastern University Northeastern Huskies  Boston  Massachusetts Colonial Athletic Association")
# College.find_or_create_by(name: "Northern Arizona University Northern Arizona Lumberjacks  Flagstaff Arizona Big Sky Conference")
# College.find_or_create_by(name: "University of Northern Colorado Northern Colorado Bears Greeley Colorado  Big Sky Conference")
# College.find_or_create_by(name: "Northern Illinois University  Northern Illinois Huskies DeKalb  Illinois  Mid-American Conference")
# College.find_or_create_by(name: "University of Northern Iowa Northern Iowa Panthers  Cedar Falls Iowa  Missouri Valley Conference")
# College.find_or_create_by(name: "Northwestern State University Northwestern State Demons and Lady Demons Natchitoches  Louisiana Southland Conference")
# College.find_or_create_by(name: "Northwestern University Northwestern Wildcats Evanston  Illinois  Big Ten Conference")
# College.find_or_create_by(name: "University of Notre Dame  Notre Dame Fighting Irish South Bend  Indiana Atlantic Coast Conference")
# College.find_or_create_by(name: "Oakland University  Oakland Golden Grizzlies  Rochester Michigan  Horizon League")
# College.find_or_create_by(name: "Ohio University Ohio Bobcats  Athens  Ohio  Mid-American Conference")
# College.find_or_create_by(name: "Ohio State University Ohio State Buckeyes Columbus  Ohio  Big Ten Conference")
# College.find_or_create_by(name: "University of Oklahoma  Oklahoma Sooners  Norman  Oklahoma  Big 12 Conference")
# College.find_or_create_by(name: "Oklahoma State University–Stillwater  Oklahoma State Cowboys and Cowgirls Stillwater  Oklahoma  Big 12 Conference")
# College.find_or_create_by(name: "Old Dominion University Old Dominion Monarchs and Lady Monarchs Norfolk Virginia  Conference USA")
# College.find_or_create_by(name: "Oral Roberts University Oral Roberts Golden Eagles  Tulsa Oklahoma  Southland Conference")
# College.find_or_create_by(name: "University of Oregon  Oregon Ducks  Eugene  Oregon  Pacific-12 Conference")
# College.find_or_create_by(name: "Oregon State University Oregon State Beavers  Corvallis Oregon  Pacific-12 Conference")
# College.find_or_create_by(name: "University of the Pacific Pacific Tigers  Stockton  California  West Coast Conference")
# College.find_or_create_by(name: "University of Pennsylvania  Penn Quakers  Philadelphia  Pennsylvania  Ivy League")
# College.find_or_create_by(name: "Pennsylvania State University Penn State Nittany Lions[A 25]  State College Pennsylvania  Big Ten Conference")
# College.find_or_create_by(name: "Pepperdine University Pepperdine Waves  Malibu  California  West Coast Conference")
# College.find_or_create_by(name: "University of Pittsburgh  Pittsburgh Panthers[A 26] Pittsburgh  Pennsylvania  Atlantic Coast Conference")
# College.find_or_create_by(name: "University of Portland  Portland Pilots Portland  Oregon  West Coast Conference")
# College.find_or_create_by(name: "Portland State University Portland State Vikings  Portland  Oregon  Big Sky Conference")
# College.find_or_create_by(name: "Prairie View A&M University Prairie View A&M Panthers and Lady Panthers Prairie View  Texas Southwestern Athletic Conference")
# College.find_or_create_by(name: "Presbyterian College  Presbyterian Blue Hose  Clinton South Carolina  Big South Conference")
# College.find_or_create_by(name: "Princeton University  Princeton Tigers  Princeton New Jersey  Ivy League")
# College.find_or_create_by(name: "Providence College  Providence Friars Providence  Rhode Island  Big East Conference")
# College.find_or_create_by(name: "Purdue University Purdue Boilermakers West Lafayette  Indiana Big Ten Conference")
# College.find_or_create_by(name: "Quinnipiac University Quinnipiac Bobcats  Hamden  Connecticut Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "Radford University  Radford Highlanders Radford Virginia  Big South Conference")
# College.find_or_create_by(name: "University of Rhode Island  Rhode Island Rams Kingston  Rhode Island  Atlantic 10 Conference")
# College.find_or_create_by(name: "Rice University Rice Owls Houston Texas Conference USA")
# College.find_or_create_by(name: "University of Richmond  Richmond Spiders  Richmond  Virginia  Atlantic 10 Conference")
# College.find_or_create_by(name: "Rider University  Rider Broncs  Lawrenceville New Jersey  Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "Robert Morris University  Robert Morris Colonials Moon Township Pennsylvania  Northeast Conference")
# College.find_or_create_by(name: "Rutgers University  Rutgers Scarlet Knights New Brunswick New Jersey  American Athletic Conference[A 27]")
# College.find_or_create_by(name: "Sacred Heart University Sacred Heart Pioneers Fairfield Connecticut Northeast Conference")
# College.find_or_create_by(name: "St. Bonaventure University  St. Bonaventure Bonnies St. Bonaventure New York  Atlantic 10 Conference")
# College.find_or_create_by(name: "St. Francis College St. Francis Terriers[A 28]  Brooklyn  New York  Northeast Conference")
# College.find_or_create_by(name: "Saint Francis University  Saint Francis Red Flash[A 29] Loretto Pennsylvania  Northeast Conference")
# College.find_or_create_by(name: "St. John's University St. John's Red Storm[A 30]  Jamaica New York  Big East Conference")
# College.find_or_create_by(name: "Saint Joseph's University Saint Joseph's Hawks[A 31]  Philadelphia  Pennsylvania  Atlantic 10 Conference")
# College.find_or_create_by(name: "Saint Louis University  Saint Louis Billikens St. Louis Missouri  Atlantic 10 Conference")
# College.find_or_create_by(name: "Saint Mary's College of California  Saint Mary's Gaels  Moraga  California  West Coast Conference")
# College.find_or_create_by(name: "Saint Peter's University  Saint Peter's Peacocks and Peahens  Jersey City New Jersey  Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "Sam Houston State University  Sam Houston State Bearkats  Huntsville  Texas Southland Conference")
# College.find_or_create_by(name: "Samford University  Samford Bulldogs  Homewood  Alabama Southern Conference")
# College.find_or_create_by(name: "University of San Diego San Diego Toreros San Diego California  West Coast Conference")
# College.find_or_create_by(name: "San Diego State University  San Diego State Aztecs  San Diego California  Mountain West Conference")
# College.find_or_create_by(name: "University of San Francisco San Francisco Dons  San Francisco California  West Coast Conference")
# College.find_or_create_by(name: "San Jose State University San Jose State Spartans San Jose  California  Mountain West Conference")
# College.find_or_create_by(name: "Santa Clara University  Santa Clara Broncos Santa Clara California  West Coast Conference")
# College.find_or_create_by(name: "Savannah State University Savannah State Tigers and Lady Tigers Savannah  Georgia Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "Seattle University  Seattle Redhawks  Seattle Washington  Western Athletic Conference")
# College.find_or_create_by(name: "Seton Hall University Seton Hall Pirates  South Orange  New Jersey  Big East Conference")
# College.find_or_create_by(name: "Siena College Siena Saints  Loudonville New York  Metro Atlantic Athletic Conference")
# College.find_or_create_by(name: "University of South Alabama South Alabama Jaguars Mobile  Alabama Sun Belt Conference")
# College.find_or_create_by(name: "University of South Carolina  South Carolina Gamecocks  Columbia  South Carolina  Southeastern Conference")
# College.find_or_create_by(name: "South Carolina State University South Carolina State Bulldogs and Lady Bulldogs Orangeburg  South Carolina  Mid-Eastern Athletic Conference")
# College.find_or_create_by(name: "University of South Carolina Upstate  South Carolina Upstate Spartans[A 32] Spartanburg South Carolina  Atlantic Sun Conference")
# College.find_or_create_by(name: "University of South Dakota  South Dakota Coyotes  Vermillion  South Dakota  The Summit League")
# College.find_or_create_by(name: "South Dakota State University South Dakota State Jackrabbits  Brookings South Dakota  The Summit League")
# College.find_or_create_by(name: "University of South Florida South Florida Bulls Tampa Florida American Athletic Conference")
# College.find_or_create_by(name: "Southeast Missouri State University Southeast Missouri Redhawks Cape Girardeau  Missouri  Ohio Valley Conference")
# College.find_or_create_by(name: "Southeastern Louisiana University Southeastern Louisiana Lions and Lady Lions Hammond Louisiana Southland Conference")
# College.find_or_create_by(name: "University of Southern California USC Trojans[A 33][A 34] Los Angeles California  Pacific-12 Conference")
# College.find_or_create_by(name: "Southern Illinois University Carbondale Southern Illinois Salukis Carbondale  Illinois  Missouri Valley Conference")
# College.find_or_create_by(name: "Southern Illinois University Edwardsville SIU Edwardsville Cougars[A 35]  Edwardsville  Illinois  Ohio Valley Conference")
# College.find_or_create_by(name: "Southern Methodist University SMU Mustangs  University Park Texas American Athletic Conference")
# College.find_or_create_by(name: "University of Southern Mississippi  Southern Miss Golden Eagles Hattiesburg Mississippi Conference USA")
# College.find_or_create_by(name: "Southern University Southern Jaguars and Lady Jaguars Baton Rouge Louisiana Southwestern Athletic Conference")
# College.find_or_create_by(name: "Southern Utah University  Southern Utah Thunderbirds and Lady Thunderbirds  Cedar City  Utah  Big Sky Conference")
# College.find_or_create_by(name: "Stanford University Stanford Cardinal Palo Alto California  Pacific-12 Conference")
# College.find_or_create_by(name: "Stephen F. Austin State University  Stephen F. Austin Lumberjacks and Ladyjacks Nacogdoches Texas Southland Conference")
# College.find_or_create_by(name: "Stetson University  Stetson Hatters DeLand  Florida Atlantic Sun Conference")
# College.find_or_create_by(name: "Stony Brook University  Stony Brook Seawolves Stony Brook New York  America East Conference")
# College.find_or_create_by(name: "Syracuse University Syracuse Orange Syracuse  New York  Atlantic Coast Conference")
# College.find_or_create_by(name: "Temple University Temple Owls Philadelphia  Pennsylvania  American Athletic Conference")
# College.find_or_create_by(name: "University of Tennessee Tennessee Volunteers and Lady Vols[A 36]  Knoxville Tennessee Southeastern Conference")
# College.find_or_create_by(name: "University of Tennessee at Chattanooga  Chattanooga Mocs and Lady Mocs  Chattanooga Tennessee Southern Conference")
# College.find_or_create_by(name: "University of Tennessee at Martin Tennessee–Martin Skyhawks Martin  Tennessee Ohio Valley Conference")
# College.find_or_create_by(name: "Tennessee State University  Tennessee State Tigers and Lady Tigers  Nashville Tennessee Ohio Valley Conference")
# College.find_or_create_by(name: "Tennessee Technological University  Tennessee Tech Golden Eagles  Cookeville  Tennessee Ohio Valley Conference")
# College.find_or_create_by(name: "Texas A&M University  Texas A&M Aggies  College Station Texas Southeastern Conference")
# College.find_or_create_by(name: "Texas A&M University–Corpus Christi Texas A&M–Corpus Christi Islanders  Corpus Christi  Texas Southland Conference")
# College.find_or_create_by(name: "University of Texas at Arlington  UT Arlington Mavericks  Arlington Texas Sun Belt Conference")
# College.find_or_create_by(name: "University of Texas at Austin Texas Longhorns Austin  Texas Big 12 Conference")
# College.find_or_create_by(name: "Texas Christian University  TCU Horned Frogs and Lady Frogs Fort Worth  Texas Big 12 Conference")
# College.find_or_create_by(name: "University of Texas at El Paso  UTEP Miners El Paso Texas Conference USA")
# College.find_or_create_by(name: "University of Texas–Pan American  UTPA Broncs and Lady Broncs Edinburg  Texas Western Athletic Conference")
# College.find_or_create_by(name: "University of Texas at San Antonio  UTSA Roadrunners  San Antonio Texas Conference USA")
# College.find_or_create_by(name: "Texas Southern University Texas Southern Tigers and Lady Tigers Houston Texas Southwestern Athletic Conference")
# College.find_or_create_by(name: "Texas State University  Texas State Bobcats San Marcos  Texas Sun Belt Conference")
# College.find_or_create_by(name: "Texas Tech University Texas Tech Red Raiders[A 37]  Lubbock Texas Big 12 Conference")
# College.find_or_create_by(name: "University of Toledo  Toledo Rockets  Toledo  Ohio  Mid-American Conference")
# College.find_or_create_by(name: "Towson University Towson Tigers Towson  Maryland  Colonial Athletic Association")
# College.find_or_create_by(name: "Troy University Troy Trojans  Troy  Alabama Sun Belt Conference")
# College.find_or_create_by(name: "Tulane University Tulane Green Wave New Orleans Louisiana Conference USA[A 5]")
# College.find_or_create_by(name: "University of Tulsa Tulsa Golden Hurricane  Tulsa Oklahoma  Conference USA[A 5]")
# College.find_or_create_by(name: "United States Air Force Academy Air Force Falcons Colorado Springs  Colorado  Mountain West Conference")
# College.find_or_create_by(name: "United States Military Academy  Army Black Knights  West Point  New York  Patriot League")
# College.find_or_create_by(name: "United States Naval Academy Navy Midshipmen Annapolis Maryland  Patriot League")
# College.find_or_create_by(name: "University of Utah  Utah Utes[A 38] Salt Lake City  Utah  Pacific-12 Conference")
# College.find_or_create_by(name: "Utah State University Utah State Aggies Logan Utah  Mountain West Conference")
# College.find_or_create_by(name: "Utah Valley University  Utah Valley Wolverines  Orem  Utah  Western Athletic Conference")
# College.find_or_create_by(name: "Valparaiso University Valparaiso Crusaders  Valparaiso  Indiana Horizon League")
# College.find_or_create_by(name: "Vanderbilt University Vanderbilt Commodores Nashville Tennessee Southeastern Conference")
# College.find_or_create_by(name: "University of Vermont Vermont Catamounts  Burlington  Vermont America East Conference")
# College.find_or_create_by(name: "Villanova University  Villanova Wildcats  Radnor Township Pennsylvania  Big East Conference")
# College.find_or_create_by(name: "University of Virginia  Virginia Cavaliers  Charlottesville Virginia  Atlantic Coast Conference")
# College.find_or_create_by(name: "Virginia Commonwealth University  VCU Rams  Richmond  Virginia  Atlantic 10 Conference")
# College.find_or_create_by(name: "Virginia Military Institute VMI Keydets Lexington Virginia  Big South Conference[A 6]")
# College.find_or_create_by(name: "Virginia Tech Virginia Tech Hokies  Blacksburg  Virginia  Atlantic Coast Conference")
# College.find_or_create_by(name: "Wagner College  Wagner Seahawks Staten Island New York  Northeast Conference")
# College.find_or_create_by(name: "Wake Forest University  Wake Forest Demon Deacons Winston-Salem North Carolina  Atlantic Coast Conference")
# College.find_or_create_by(name: "University of Washington  Washington Huskies  Seattle Washington  Pacific-12 Conference")
# College.find_or_create_by(name: "Washington State University Washington State Cougars  Pullman Washington  Pacific-12 Conference")
# College.find_or_create_by(name: "Weber State University  Weber State Wildcats  Ogden Utah  Big Sky Conference")
# College.find_or_create_by(name: "West Virginia University  West Virginia Mountaineers  Morgantown  West Virginia Big 12 Conference")
# College.find_or_create_by(name: "Western Carolina University Western Carolina Catamounts Cullowhee North Carolina  Southern Conference")
# College.find_or_create_by(name: "Western Illinois University Western Illinois Leathernecks Macomb  Illinois  The Summit League")
# College.find_or_create_by(name: "Western Kentucky University WKU Hilltoppers and Lady Toppers  Bowling Green Kentucky  Sun Belt Conference[A 39]")
# College.find_or_create_by(name: "Western Michigan University Western Michigan Broncos  Kalamazoo Michigan  Mid-American Conference")
# College.find_or_create_by(name: "Wichita State University  Wichita State Shockers  Wichita Kansas  Missouri Valley Conference")
# College.find_or_create_by(name: "College of William & Mary William & Mary Tribe  Williamsburg  Virginia  Colonial Athletic Association")
# College.find_or_create_by(name: "Winthrop University Winthrop Eagles Rock Hill South Carolina  Big South Conference")
# College.find_or_create_by(name: "University of Wisconsin–Green Bay Green Bay Phoenix[A 40] Green Bay Wisconsin Horizon League")
# College.find_or_create_by(name: "University of Wisconsin–Madison Wisconsin Badgers Madison Wisconsin Big Ten Conference")
# College.find_or_create_by(name: "University of Wisconsin–Milwaukee Milwaukee Panthers[A 41]  Milwaukee Wisconsin Horizon League")
# College.find_or_create_by(name: "Wofford College Wofford Terriers  Spartanburg South Carolina  Southern Conference")
# College.find_or_create_by(name: "Wright State University Wright State Raiders  Fairborn  Ohio  Horizon League")
# College.find_or_create_by(name: "University of Wyoming Wyoming Cowboys and Cowgirls  Laramie Wyoming Mountain West Conference")
# College.find_or_create_by(name: "Xavier University Xavier Musketeers Cincinnati  Ohio  Big East Conference")
# College.find_or_create_by(name: "Yale University Yale Bulldogs New Haven Connecticut Ivy League")
# College.find_or_create_by(name: "Youngstown State University Youngstown State Penguins Youngstown  Ohio  Horizon League")